/**
 * The "Agent Cleaner" — a standalone PowerShell script an admin runs on a
 * machine to fully remove every artifact the CEP agent creates. Built for the
 * case where the agent was removed but left files behind, or is broken and the
 * normal uninstall won't run. It reports how many artifacts it found, how many
 * it removed, and the exact path of anything it could not remove. After each
 * run it waits for -r (run again) or -c (close the window).
 *
 * Artifact names come straight from the agent/installer:
 *   service        CepAgent            (installer/Package.wxs)
 *   scheduled task CepAgentUpdater     (AgentPaths.UpdaterTaskName)
 *   install dir    %ProgramFiles%\CepAgent
 *   data dir       %ProgramData%\CepAgent   (AgentPaths.Root)
 *   service reg    HKLM\SYSTEM\CurrentControlSet\Services\CepAgent
 * The script takes no server URL or token — it is purely local cleanup.
 */
export function buildAgentCleanerPs1(): string {
  return [
    '# CEP Agent Cleaner',
    '# Fully removes the CEP Compliance Agent and every file it creates from THIS',
    '# machine. Use it when the agent was removed but left files behind, or when the',
    '# agent is broken. Safe to run repeatedly. Run as Administrator.',
    '',
    '$ErrorActionPreference = "SilentlyContinue"',
    '',
    '# --- self-elevate ---',
    '$wid = [Security.Principal.WindowsIdentity]::GetCurrent()',
    '$principal = New-Object Security.Principal.WindowsPrincipal($wid)',
    'if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {',
    '  Start-Process powershell -Verb RunAs -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`""',
    '  return',
    '}',
    '',
    '$ServiceName = "CepAgent"',
    '$TaskName    = "CepAgentUpdater"',
    '$InstallDir  = Join-Path $env:ProgramFiles "CepAgent"',
    '$DataDir     = Join-Path $env:ProgramData "CepAgent"',
    '$SvcRegKey   = "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\CepAgent"',
    '',
    'function Invoke-CepClean {',
    '  Write-Host ""',
    '  Write-Host "============================================" -ForegroundColor Cyan',
    '  Write-Host "  CEP Agent Cleaner" -ForegroundColor Cyan',
    '  Write-Host "============================================" -ForegroundColor Cyan',
    '',
    '  # Stop the service and kill any running agent processes so files unlock.',
    '  Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue',
    '  foreach ($p in @("CepAgent","CepAgent.Updater")) {',
    '    Get-Process -Name $p -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue',
    '  }',
    '  Start-Sleep -Milliseconds 400',
    '',
    '  $report = New-Object System.Collections.Generic.List[object]',
    '  $found = 0; $removed = 0; $failed = 0',
    '',
    '  # --- Windows service ---',
    '  if (Get-Service -Name $ServiceName -ErrorAction SilentlyContinue) {',
    '    $found++',
    '    & sc.exe delete $ServiceName *> $null',
    '    Start-Sleep -Milliseconds 300',
    '    if (Get-Service -Name $ServiceName -ErrorAction SilentlyContinue) {',
    '      $failed++; $report.Add([pscustomobject]@{ Kind="Service"; Path="Service: $ServiceName"; Status="FAILED: still present" })',
    '    } else {',
    '      $removed++; $report.Add([pscustomobject]@{ Kind="Service"; Path="Service: $ServiceName"; Status="Removed" })',
    '    }',
    '  }',
    '',
    '  # --- scheduled task ---',
    '  if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {',
    '    $found++',
    '    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue',
    '    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {',
    '      $failed++; $report.Add([pscustomobject]@{ Kind="Task"; Path="Scheduled Task: $TaskName"; Status="FAILED: still present" })',
    '    } else {',
    '      $removed++; $report.Add([pscustomobject]@{ Kind="Task"; Path="Scheduled Task: $TaskName"; Status="Removed" })',
    '    }',
    '  }',
    '',
    '  # --- every file under the install + data directories (reported individually) ---',
    '  foreach ($base in @($InstallDir, $DataDir)) {',
    '    if (Test-Path -LiteralPath $base) {',
    '      foreach ($f in (Get-ChildItem -LiteralPath $base -Recurse -File -Force -ErrorAction SilentlyContinue)) {',
    '        $found++',
    '        try {',
    '          Remove-Item -LiteralPath $f.FullName -Force -ErrorAction Stop',
    '          $removed++; $report.Add([pscustomobject]@{ Kind="File"; Path=$f.FullName; Status="Removed" })',
    '        } catch {',
    '          $failed++; $report.Add([pscustomobject]@{ Kind="File"; Path=$f.FullName; Status=("FAILED: " + $_.Exception.Message) })',
    '        }',
    '      }',
    '      # remove the now-empty directory tree (best effort)',
    '      Remove-Item -LiteralPath $base -Recurse -Force -ErrorAction SilentlyContinue',
    '    }',
    '  }',
    '',
    '  # --- leftover service registry key ---',
    '  if (Test-Path -LiteralPath $SvcRegKey) {',
    '    $found++',
    '    try {',
    '      Remove-Item -LiteralPath $SvcRegKey -Recurse -Force -ErrorAction Stop',
    '      $removed++; $report.Add([pscustomobject]@{ Kind="Registry"; Path=$SvcRegKey; Status="Removed" })',
    '    } catch {',
    '      $failed++; $report.Add([pscustomobject]@{ Kind="Registry"; Path=$SvcRegKey; Status=("FAILED: " + $_.Exception.Message) })',
    '    }',
    '  }',
    '',
    '  # --- report ---',
    '  if ($found -eq 0) {',
    '    Write-Host ""',
    '    Write-Host "Nothing found - this machine is already clean of CEP agent files." -ForegroundColor Green',
    '  } else {',
    '    Write-Host ""',
    '    # FAILED rows sort first so a stuck file and its path are obvious.',
    '    ($report | Sort-Object Status | Format-Table Kind, Status, Path -AutoSize -Wrap | Out-String -Width 4096).TrimEnd() | Write-Host',
    '    Write-Host ""',
    '    Write-Host ("Found:   {0}" -f $found)',
    '    Write-Host ("Removed: {0}" -f $removed) -ForegroundColor Green',
    '    if ($failed -gt 0) {',
    '      Write-Host ("Failed:  {0}  (see the FAILED rows above for the exact path)" -f $failed) -ForegroundColor Red',
    '    } else {',
    '      Write-Host  "Failed:  0"',
    '    }',
    '  }',
    '}',
    '',
    '# Run, then wait for -r (run again) or -c (close).',
    'while ($true) {',
    '  Invoke-CepClean',
    '  Write-Host ""',
    '  $ans = ""',
    '  while ($ans -ne "-r" -and $ans -ne "-c") {',
    '    $ans = (Read-Host "Type -r to run the cleaner again, or -c to close").Trim().ToLower()',
    '  }',
    '  if ($ans -eq "-c") { break }',
    '}',
    'Stop-Process -Id $PID',
    '',
  ].join('\r\n');
}
