import { sysAccess, type SeedEntry } from '../types';

const PW = 'Security Settings > Account Policies > Password Policy';
const LO = 'Security Settings > Account Policies > Account Lockout Policy';

const pw = sysAccess(PW);
const lo = sysAccess(LO);

export const accountPolicyEntries: SeedEntry[] = [
  pw(
    'sec_pw_history',
    '1.1.1',
    'Enforce password history',
    'PasswordHistorySize',
    24,
    'Remembers previous passwords (24 recommended) so users cannot rotate back to a recently used password.',
    'Low breakage risk. Users who habitually cycle a small set of passwords will need genuinely new ones.',
    { maps: { n171: ['3.5.8!'], n53: ['IA-5!'], hipaa: ['164.308(a)(5)(ii)(D)!'], soc2: ['CC6.1'] } },
  ),
  pw(
    'sec_pw_maxage',
    '1.1.2',
    'Maximum password age',
    'MaximumPasswordAge',
    365,
    'Forces a password change after this many days (365 or fewer, but not 0/never, per CIS).',
    'When a password expires on a machine that is rarely logged into interactively (kiosks, service consoles), users can be surprised at the login screen. Scheduled tasks and services using that account will fail after expiry until updated.',
    { maps: { n171: ['3.5.7', '3.5.8'], n53: ['IA-5!'], hipaa: ['164.308(a)(5)(ii)(D)!'], soc2: ['CC6.1'] } },
  ),
  pw(
    'sec_pw_minage',
    '1.1.3',
    'Minimum password age',
    'MinimumPasswordAge',
    1,
    'Prevents changing a password again for this many days (1 recommended), which stops users from burning through the history list in minutes to return to an old favorite.',
    'A user with a compromised password must contact an admin to reset it before the minimum age elapses. Helpdesk resets are unaffected.',
    { maps: { n171: ['3.5.8'], n53: ['IA-5!'], hipaa: ['164.308(a)(5)(ii)(D)'], soc2: ['CC6.1'] } },
  ),
  pw(
    'sec_pw_minlen',
    '1.1.4',
    'Minimum password length',
    'MinimumPasswordLength',
    14,
    'Requires passwords of at least this many characters (14 recommended). Length is the single strongest lever against offline cracking of captured hashes.',
    'Users with short passwords keep working until their next change, then must pick a longer one. Legacy LM-hash-era systems and some ancient line-of-business logins may cap length; verify before enforcing on machines running pre-2000s software.',
    { maps: { n171: ['3.5.7!'], n53: ['IA-5!'], hipaa: ['164.308(a)(5)(ii)(D)!'], soc2: ['CC6.1'] } },
  ),
  pw(
    'sec_pw_complexity',
    '1.1.5',
    'Password must meet complexity requirements',
    'PasswordComplexity',
    1,
    'Requires passwords to combine at least three of: uppercase, lowercase, digits, symbols, and to not contain the account name.',
    'Low breakage risk; only affects the next password change. Some users will need help choosing compliant passwords.',
    { maps: { n171: ['3.5.7!'], n53: ['IA-5!'], hipaa: ['164.308(a)(5)(ii)(D)!'], soc2: ['CC6.1'] } },
  ),
  pw(
    'sec_pw_cleartext',
    '1.1.7',
    'Store passwords using reversible encryption',
    'ClearTextPassword',
    0,
    'When disabled (recommended), Windows never stores passwords in a reversibly-encrypted (near-plaintext) form.',
    'Only breaks CHAP-based remote access and IIS Digest authentication configured to require reversible passwords — both are rare and legacy. Leave disabled unless one of those is documented.',
    { maps: { n171: ['3.5.10!'], n53: ['IA-5!'], hipaa: ['164.312(a)(2)(iv)', '164.308(a)(5)(ii)(D)'], soc2: ['CC6.1'] } },
  ),
  lo(
    'sec_lockout_duration',
    '1.2.1',
    'Account lockout duration',
    'LockoutDuration',
    15,
    'How many minutes a locked-out account stays locked before unlocking automatically (15 recommended; 0 means an admin must unlock manually).',
    'On workgroup machines with a single admin account, an aggressive lockout combined with a forgotten password can lock the only usable account — keep a break-glass account. Printers/scanners or apps retrying a stale saved credential against the machine can keep re-locking the account.',
    { maps: { n171: ['3.1.8!'], n53: ['AC-7!'], hipaa: ['164.308(a)(5)(ii)(C)'], soc2: ['CC6.1'] } },
  ),
  lo(
    'sec_lockout_threshold',
    '1.2.2',
    'Account lockout threshold',
    'LockoutBadCount',
    5,
    'Number of failed sign-in attempts (5 or fewer, but not 0) before the account locks. Blocks online password guessing and spraying.',
    'Devices with stored stale credentials (scan-to-SMB scanners, mapped drives, scheduled tasks, mobile mail clients) will lock the account repeatedly until the stored password is fixed. An attacker can also deliberately lock accounts (denial of service) by spraying bad passwords.',
    { maps: { n171: ['3.1.8!'], n53: ['AC-7!'], hipaa: ['164.308(a)(5)(ii)(C)!'], soc2: ['CC6.1'] } },
  ),
  lo(
    'sec_lockout_window',
    '1.2.3',
    'Reset account lockout counter after',
    'ResetLockoutCount',
    15,
    'Minutes after which the failed-attempt counter resets to zero (15 recommended). Must be less than or equal to the lockout duration.',
    'Low breakage risk by itself; interacts with the threshold above — see that setting for the stale-credential lockout loop.',
    { maps: { n171: ['3.1.8!'], n53: ['AC-7!'], hipaa: ['164.308(a)(5)(ii)(C)'], soc2: ['CC6.1'] } },
  ),
  lo(
    'sec_lockout_adminaccount',
    '1.2.4',
    'Allow Administrator account lockout',
    'AllowAdministratorLockout',
    1,
    'Extends lockout to the built-in Administrator account (RID 500), closing the classic loophole where that one account could be brute-forced forever.',
    'On a workgroup machine where the built-in Administrator is the ONLY admin account, an attacker (or a broken device retrying a bad password) can lock you out of the machine entirely for the lockout duration. Create a second admin account first. Requires Windows 11 22H2 / Server 2022+ with the October 2022 update; older builds ignore it.',
    { minBuild: 20348, maps: { n171: ['3.1.8'], n53: ['AC-7!'], soc2: ['CC6.1'] } },
  ),
  sysAccess('Security Settings > Local Policies > Security Options')(
    'sec_accounts_admin_enabled',
    '2.3.1.1',
    'Accounts: Administrator account status',
    'EnableAdminAccount',
    0,
    'Disables the built-in Administrator account (RID 500). Attackers target this well-known account because it cannot be locked out on older builds.',
    'CRITICAL on workgroup/non-domain machines: if this is the only administrative account, disabling it locks everyone out of admin functions. Always confirm another local admin exists before enforcing. Safe Mode still permits the built-in admin to log on.',
    { maps: { n171: ['3.1.1', '3.5.5'], n53: ['AC-2!'], hipaa: ['164.308(a)(3)(i)'], soc2: ['CC6.2'] } },
  ),
  sysAccess('Security Settings > Local Policies > Security Options')(
    'sec_accounts_guest_enabled',
    '2.3.1.2',
    'Accounts: Guest account status',
    'EnableGuestAccount',
    0,
    'Disables the built-in Guest account so anonymous local sign-in is impossible.',
    'Breaks the legacy "guest share" pattern where a workgroup machine shares files/printers to unauthenticated neighbors. If a workgroup file share suddenly prompts for credentials after enforcement, this (with ForceGuest) is why — create a real local account for share access instead.',
    { maps: { n171: ['3.1.1!'], n53: ['AC-2!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.1'] } },
  ),
  sysAccess('Security Settings > Local Policies > Security Options')(
    'sec_accounts_rename_admin',
    '2.3.1.4',
    'Accounts: Rename administrator account',
    'NewAdministratorName',
    'LocalSecAdmin',
    'Renames the built-in Administrator account away from the well-known name attackers script against. Pick an organization-specific name; the seeded value is a placeholder to change per customer.',
    'Scripts, scheduled tasks, and documentation that reference ".\\Administrator" by name will break. The account SID (ending -500) is unchanged, so SID-based references keep working — and so do attackers who enumerate by SID; treat this as friction, not a wall.',
    { maps: { n171: ['3.1.1'], n53: ['AC-2'], soc2: ['CC6.1'] } },
  ),
  sysAccess('Security Settings > Local Policies > Security Options')(
    'sec_accounts_rename_guest',
    '2.3.1.5',
    'Accounts: Rename guest account',
    'NewGuestName',
    'LocalVisitor',
    'Renames the built-in Guest account away from its well-known name.',
    'Minimal risk; the account should also be disabled. Anything referencing "Guest" by name (rare) would break.',
    { maps: { n171: ['3.1.1'], n53: ['AC-2'], soc2: ['CC6.1'] } },
  ),
  sysAccess('Security Settings > Local Policies > Security Options')(
    'sec_network_force_logoff',
    '2.3.11.6',
    'Network security: Force logoff when logon hours expire',
    'ForceLogoffWhenHourExpire',
    1,
    'Disconnects SMB sessions with the server when the account\'s permitted logon hours end.',
    'Only matters where logon hours are actually configured (rare outside domains). Users copying a large file when hours expire lose the connection.',
    { maps: { n171: ['3.1.11'], n53: ['AC-12!'], hipaa: ['164.312(a)(2)(iii)'], soc2: ['CC6.1'] } },
  ),
  sysAccess('Security Settings > Local Policies > Security Options')(
    'sec_network_lsa_anon_lookup',
    '2.3.11.2',
    'Network access: Allow anonymous SID/Name translation',
    'LSAAnonymousNameLookup',
    0,
    'When disabled (recommended), anonymous callers cannot translate a SID to an account name — e.g. resolving S-1-5-...-500 to discover the renamed Administrator account.',
    'Very old management tools that enumerate accounts anonymously stop working. Renaming the admin account (above) is pointless without this.',
    { maps: { n171: ['3.1.1'], n53: ['AC-3'], soc2: ['CC6.1'] } },
  ),
];
