import { adminTemplate, EN_DIS, type SeedEntry } from '../types';

const NET = 'Administrative Templates > Network';
const RDP = 'Administrative Templates > Windows Components > Remote Desktop Services';
const WRM = 'Administrative Templates > Windows Components > Windows Remote Management (WinRM)';
const PRT = 'Administrative Templates > Printers';
const CRED = 'Administrative Templates > System > Credentials Delegation';
const DG = 'Administrative Templates > System > Device Guard';
const SYS = 'Administrative Templates > System';
const FW = 'Windows Defender Firewall with Advanced Security';

const net = adminTemplate(NET);
const rdp = adminTemplate(RDP);
const wrm = adminTemplate(WRM);
const prt = adminTemplate(PRT);
const cred = adminTemplate(CRED);
const dg = adminTemplate(DG);
const sys = adminTemplate(SYS);
const fw = adminTemplate(FW);

const TS = 'SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services';

export const adminTemplatesNetworkEntries: SeedEntry[] = [
  // --- Name resolution poisoning surface --------------------------------
  net('at_llmnr_disable', '18.5.4.2', 'Turn off multicast name resolution (LLMNR)',
    ['SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient', 'EnableMulticast', 'REG_DWORD'], 0,
    'Disables LLMNR, the broadcast fallback protocol that Responder-style tools poison to harvest NTLM hashes on the LAN.',
    'Machines that relied on LLMNR to find peers with no DNS record (typically ad-hoc \\\\hostname access to devices on flat home-style networks) must get proper DNS entries. Combine with NetBIOS hardening or attackers just poison NBNS instead.',
    { allowed: [{ value: 0, label: 'LLMNR off (secure)' }, { value: 1, label: 'LLMNR on' }],
      maps: { n171: ['3.13.1!'], n53: ['SC-7!', 'SC-20'], soc2: ['CC6.6'] } }),
  net('at_mdns_disable', '18.5.4.1', 'Turn off mDNS resolution',
    ['SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient', 'EnableMDNS', 'REG_DWORD'], 0,
    'Disables Windows mDNS resolution (the second broadcast name-resolution channel poisoners abuse).',
    'Breaks discovery of mDNS-only devices from this machine: AirPrint printers, Chromecast targets, some smart displays. Print servers with proper DNS names are unaffected.',
    { allowed: [{ value: 0, label: 'mDNS off (secure)' }, { value: 1, label: 'mDNS on' }],
      maps: { n171: ['3.13.1'], n53: ['SC-7!'], soc2: ['CC6.6'] } }),
  net('at_netbios_p2p_off', '18.5.9.1', 'Turn off Microsoft Peer-to-Peer Networking Services',
    ['SOFTWARE\\policies\\Microsoft\\Peernet', 'Disabled', 'REG_DWORD'], 1,
    'Disables the P2P grouping/PNRP services (HomeGroup-era plumbing with its own discovery chatter).',
    'None on business networks.',
    { allowed: EN_DIS, maps: { n171: ['3.4.6'], n53: ['CM-7!'], soc2: ['CC6.6'] } }),
  net('at_network_bridge_block', '18.5.11.2', 'Prohibit installation and configuration of Network Bridge',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\Network Connections', 'NC_AllowNetBridge_NLA', 'REG_DWORD'], 0,
    'Users cannot bridge two network interfaces, which would silently join separate networks (e.g., corporate wired + guest Wi-Fi).',
    'None for normal users; lab machines doing deliberate bridging need an exception.',
    { allowed: [{ value: 0, label: 'Bridge prohibited (secure)' }, { value: 1, label: 'Bridge allowed' }],
      maps: { n171: ['3.13.1', '3.1.16?'], n53: ['SC-7!'], soc2: ['CC6.6'] } }),
  net('at_ics_block', '18.5.11.3', 'Prohibit use of Internet Connection Sharing',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\Network Connections', 'NC_ShowSharedAccessUI', 'REG_DWORD'], 0,
    'Users cannot turn the machine into a NAT gateway/hotspot for other devices.',
    'Mobile-hotspot sharing from the PC stops working; none otherwise.',
    { allowed: [{ value: 0, label: 'ICS prohibited (secure)' }, { value: 1, label: 'ICS allowed' }],
      maps: { n171: ['3.13.1'], n53: ['SC-7!'], soc2: ['CC6.6'] } }),
  net('at_hardened_unc_sysvol', '18.5.14.1', 'Hardened UNC Paths: \\\\*\\SYSVOL',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkProvider\\HardenedPaths', '\\\\*\\SYSVOL', 'REG_SZ'],
    'RequireMutualAuthentication=1, RequireIntegrity=1',
    'Requires Kerberos mutual authentication and SMB signing when reading SYSVOL — blocks the MS15-011 GPO-hijack attack class.',
    'Domain-joined machines on networks where Kerberos to the DC is broken (VPN split-tunnel misconfigurations) fail to apply Group Policy. Harmless on workgroup machines (no SYSVOL access at all).',
    { maps: { n171: ['3.13.8!', '3.13.15'], n53: ['SC-8!', 'SC-23'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.7'] } }),
  net('at_hardened_unc_netlogon', '18.5.14.2', 'Hardened UNC Paths: \\\\*\\NETLOGON',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkProvider\\HardenedPaths', '\\\\*\\NETLOGON', 'REG_SZ'],
    'RequireMutualAuthentication=1, RequireIntegrity=1',
    'Same protection as the SYSVOL path, for the NETLOGON share (logon scripts).',
    'See the SYSVOL entry.',
    { maps: { n171: ['3.13.8!', '3.13.15'], n53: ['SC-8!', 'SC-23'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.7'] } }),
  net('at_wcm_block_nondomain', '18.5.21.2', 'Prohibit connection to non-domain networks when connected to domain authenticated network',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WcmSvc\\GroupPolicy', 'fBlockNonDomain', 'REG_DWORD'], 1,
    'Prevents simultaneous connections to the corporate network and an outside network (dual-homing exfiltration/bridge risk).',
    'Laptops docked on wired corporate LAN can no longer stay on a second Wi-Fi (including phone hotspots). Field laptops that legitimately use out-of-band connections need an exception policy.',
    { allowed: EN_DIS, maps: { n171: ['3.13.1', '3.1.20'], n53: ['SC-7!', 'AC-18'], soc2: ['CC6.6'] } }),
  net('at_wcm_minimize_connections', '18.5.21.1', 'Minimize the number of simultaneous connections to the Internet or a Windows Domain',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WcmSvc\\GroupPolicy', 'fMinimizeConnections', 'REG_DWORD'], 3,
    'When ethernet is connected, Wi-Fi disconnects (3 = prevent Wi-Fi when on cellular is also included).',
    'Users who expect Wi-Fi to stay associated while docked will see it drop — cosmetic in most cases.',
    { allowed: [{ value: 0, label: 'Allow all connections' }, { value: 1, label: 'Minimize' }, { value: 3, label: 'Prevent Wi-Fi on ethernet (secure)' }],
      maps: { n171: ['3.13.1'], n53: ['SC-7'], soc2: ['CC6.6'] } }),
  net('at_wifi_no_open_hotspots', '18.5.23.1', 'Do not auto-connect to suggested open hotspots',
    ['SOFTWARE\\Microsoft\\wcmsvc\\wifinetworkmanager\\config', 'AutoConnectAllowedOEM', 'REG_DWORD'], 0,
    'Stops automatic connection to open Wi-Fi hotspots and networks shared by contacts.',
    'None — this only disables risky auto-join behavior.',
    { allowed: [{ value: 0, label: 'Auto-connect off (secure)' }, { value: 1, label: 'Auto-connect on' }],
      maps: { n171: ['3.1.16?'], n53: ['AC-18!'], soc2: ['CC6.6'] } }),

  // --- RPC / remote management hardening --------------------------------
  sys('at_rpc_restrict_unauth', '18.9.36.2', 'Restrict unauthenticated RPC clients',
    ['SOFTWARE\\Policies\\Microsoft\\Windows NT\\Rpc', 'RestrictRemoteClients', 'REG_DWORD'], 1,
    'The RPC runtime rejects anonymous remote calls (1 = Authenticated).',
    'Value 2 (Authenticated without exceptions) breaks RPC-over-named-pipe scenarios and some management tools; 1 is the compatible hardening step this baseline sets.',
    { allowed: [{ value: 0, label: 'None' }, { value: 1, label: 'Authenticated (secure)' }, { value: 2, label: 'Authenticated without exceptions' }],
      maps: { n171: ['3.1.1', '3.5.2'], n53: ['AC-3', 'IA-2'], soc2: ['CC6.1'] } }),
  sys('at_rpc_ep_auth', '18.9.36.1', 'Enable RPC Endpoint Mapper Client Authentication',
    ['SOFTWARE\\Policies\\Microsoft\\Windows NT\\Rpc', 'EnableAuthEpResolution', 'REG_DWORD'], 1,
    'Clients authenticate to the endpoint mapper before resolving dynamic RPC endpoints.',
    'Interop issues only with pre-Vista era systems.',
    { allowed: EN_DIS, maps: { n171: ['3.5.2'], n53: ['IA-2'], soc2: ['CC6.1'] } }),
  sys('at_gp_no_bg_refresh_off', '18.8.21.4', 'Turn off background refresh of Group Policy: Disabled',
    ['SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System', 'DisableBkGndGroupPolicy', 'REG_DWORD'], 0,
    'Keeps background Group Policy refresh ON (value 0) so policy corrections apply without reboots.',
    'None — this preserves default refresh behavior against tampering.',
    { allowed: [{ value: 0, label: 'Background refresh on (secure)' }, { value: 1, label: 'Background refresh off' }],
      maps: { n171: ['3.4.2'], n53: ['CM-6!'], soc2: ['CC5.2'] } }),
  sys('at_gp_registry_policy_processing', '18.8.21.2', 'Configure registry policy processing (process even if unchanged)',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\Group Policy\\{35378EAC-683F-11D2-A89A-00C04FBBCFA2}', 'NoGPOListChanges', 'REG_DWORD'], 0,
    'Registry policy re-applies at every refresh even when the GPO version is unchanged (0 = process unchanged), reverting local tampering with policy keys.',
    'Slightly longer policy refresh; worth it — without this, an attacker\'s registry edits persist until a GPO version bump.',
    { allowed: [{ value: 0, label: 'Process even if unchanged (secure)' }, { value: 1, label: 'Skip unchanged' }],
      maps: { n171: ['3.4.2!'], n53: ['CM-6!'], soc2: ['CC5.2'] } }),

  // --- Remote Desktop Services -----------------------------------------
  rdp('at_rdp_no_password_saving', '18.10.57.2.2', 'Do not allow passwords to be saved (RDP client)',
    [TS, 'DisablePasswordSaving', 'REG_DWORD'], 1,
    'The Remote Desktop client will not save credentials for connections, keeping RDP passwords out of Credential Manager.',
    'Users re-enter passwords on every RDP connection. Jump-box workflows get more keystrokes; password managers fill the gap.',
    { allowed: EN_DIS, maps: { n171: ['3.5.10', '3.1.12'], n53: ['IA-5!', 'AC-17'], hipaa: ['164.312(d)'], soc2: ['CC6.1'] } }),
  rdp('at_rdp_no_drive_redirect', '18.10.57.3.3.3', 'Do not allow drive redirection',
    [TS, 'fDisableCdm', 'REG_DWORD'], 1,
    'RDP sessions cannot map the client\'s local drives into the remote session — a data-exfiltration and ransomware-inbound channel.',
    'BREAKS the common workflow of copying files to a server through an RDP session (tsclient shares). Admins must use managed file transfer or admin shares instead. Widely felt — communicate before enforcing.',
    { allowed: EN_DIS, maps: { n171: ['3.1.12', '3.13.4'], n53: ['AC-17!', 'SC-4?'], hipaa: ['164.310(b)'], soc2: ['CC6.7'] } }),
  rdp('at_rdp_prompt_password', '18.10.57.3.9.1', 'Always prompt for password upon connection',
    [TS, 'fPromptForPassword', 'REG_DWORD'], 1,
    'The RDP host always asks for the password interactively, even if the client supplied saved credentials.',
    'Automated RDP logins with embedded credentials (some kiosk/test rigs) stop working.',
    { allowed: EN_DIS, maps: { n171: ['3.5.2', '3.1.12'], n53: ['IA-2!', 'AC-17'], hipaa: ['164.312(d)'], soc2: ['CC6.1'] } }),
  rdp('at_rdp_rpc_secure', '18.10.57.3.9.2', 'Require secure RPC communication',
    [TS, 'fEncryptRPCTraffic', 'REG_DWORD'], 1,
    'RDP host requires encrypted, authenticated RPC for its management channels.',
    'None on supported clients.',
    { allowed: EN_DIS, maps: { n171: ['3.13.8!'], n53: ['SC-8!', 'AC-17'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.7'] } }),
  rdp('at_rdp_security_layer_ssl', '18.10.57.3.9.3', 'Require use of specific security layer: SSL (TLS 1.0+)',
    [TS, 'SecurityLayer', 'REG_DWORD'], 2,
    'Forces TLS as the RDP transport security layer (2 = SSL) instead of legacy RDP encryption.',
    'Pre-Vista RDP clients cannot connect (extinct). Certificate warnings appear on clients if the host uses the self-signed cert — expected without an internal CA.',
    { allowed: [{ value: 0, label: 'Negotiate' }, { value: 1, label: 'RDP legacy' }, { value: 2, label: 'SSL/TLS (secure)' }],
      maps: { n171: ['3.13.8!', '3.1.13'], n53: ['SC-8!', 'AC-17!'], hipaa: ['164.312(e)(1)!'], soc2: ['CC6.7'] } }),
  rdp('at_rdp_require_nla', '18.10.57.3.9.4', 'Require user authentication using Network Level Authentication',
    [TS, 'UserAuthentication', 'REG_DWORD'], 1,
    'Connections must authenticate (NLA/CredSSP) BEFORE a session or login screen is created — the mitigation class that stopped BlueKeep-style pre-auth exploits.',
    'Very old RDP clients (XP-era, some thin terminals) cannot connect. Users whose password expired cannot reset it at the RDP login screen (no pre-session UI) — they need console access or another reset path.',
    { allowed: EN_DIS, maps: { n171: ['3.1.12!', '3.5.2!'], n53: ['AC-17!', 'IA-2!'], hipaa: ['164.312(d)!'], soc2: ['CC6.1', 'CC6.6'] } }),
  rdp('at_rdp_encryption_high', '18.10.57.3.9.5', 'Set client connection encryption level: High',
    [TS, 'MinEncryptionLevel', 'REG_DWORD'], 3,
    '128-bit encryption for legacy RDP security layer sessions (3 = High).',
    'Only affects clients that negotiated legacy RDP encryption; none with TLS enforced.',
    { allowed: [{ value: 1, label: 'Low' }, { value: 2, label: 'Client compatible' }, { value: 3, label: 'High (secure)' }],
      maps: { n171: ['3.13.8!'], n53: ['SC-8!'], hipaa: ['164.312(e)(2)(ii)'], soc2: ['CC6.7'] } }),
  rdp('at_rdp_idle_timeout', '18.10.57.3.10.1', 'Set time limit for active but idle Remote Desktop Services sessions',
    [TS, 'MaxIdleTime', 'REG_DWORD'], 900000,
    'Idle RDP sessions disconnect after 15 minutes (value in milliseconds), releasing the console and shrinking hijack windows.',
    'Long-running interactive tasks watched occasionally (installers, imports) get disconnected — the session keeps running, reconnect resumes it. Raise per-tenant for legitimate monitoring consoles.',
    { maps: { n171: ['3.1.11!', '3.1.10'], n53: ['AC-12!', 'AC-11'], hipaa: ['164.312(a)(2)(iii)!'], soc2: ['CC6.1'] } }),
  rdp('at_rdp_disconnect_timeout', '18.10.57.3.10.2', 'Set time limit for disconnected sessions',
    [TS, 'MaxDisconnectionTime', 'REG_DWORD'], 60000,
    'Disconnected sessions are logged off after 1 minute, freeing licenses and closing abandoned privileged sessions.',
    'Work left running in a disconnected session (long copy, unsaved documents) is TERMINATED at logoff. Server admins who intentionally disconnect long jobs must switch to scheduled tasks or raise this limit in a sub-policy.',
    { maps: { n171: ['3.1.11!'], n53: ['AC-12!'], hipaa: ['164.312(a)(2)(iii)'], soc2: ['CC6.1'] } }),
  rdp('at_rdp_delete_temp_on_exit', '18.10.57.3.11.1', 'Do not delete temp folders upon exit: Disabled',
    [TS, 'DeleteTempDirsOnExit', 'REG_DWORD'], 1,
    'Per-session RDP temp folders are deleted at logoff (confusingly, 1 = do delete).',
    'None.',
    { allowed: EN_DIS, maps: { n53: ['SC-4'], soc2: ['CC6.7'] } }),
  rdp('at_ra_no_solicited', '18.10.57.2.1', 'Configure Solicited Remote Assistance: Disallow',
    [TS, 'fAllowToGetHelp', 'REG_DWORD'], 0,
    'Users cannot invite outside parties to control their machine via Windows Remote Assistance (a favorite social-engineering channel).',
    'Helpdesks actually using Windows Remote Assistance (msra) lose it — professional remote-support tools are unaffected.',
    { allowed: [{ value: 0, label: 'Disallowed (secure)' }, { value: 1, label: 'Allowed' }],
      maps: { n171: ['3.1.12!'], n53: ['AC-17!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.6'] } }),
  rdp('at_ra_no_unsolicited', '18.10.57.2.3', 'Configure Offer Remote Assistance: Disallow',
    [TS, 'fAllowUnsolicited', 'REG_DWORD'], 0,
    'Blocks unsolicited "offer" Remote Assistance to this machine.',
    'Same as solicited RA — only affects the built-in msra tooling.',
    { allowed: [{ value: 0, label: 'Disallowed (secure)' }, { value: 1, label: 'Allowed' }],
      maps: { n171: ['3.1.12!'], n53: ['AC-17!'], soc2: ['CC6.6'] } }),
  sys('at_uac_remote_restrictions', '18.4.1', 'Apply UAC restrictions to local accounts on network logons (LocalAccountTokenFilterPolicy)',
    ['SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System', 'LocalAccountTokenFilterPolicy', 'REG_DWORD'], 0,
    'Local admin accounts get a FILTERED token over the network (0 = filtered), so pass-the-hash with a local admin credential cannot execute admin actions remotely.',
    'BREAKS remote admin via local accounts: psexec/WMI/admin$ with a local (non-domain) admin fails "access denied". Workgroup-managed fleets and some RMM deployment flows rely on exactly this — verify your management path uses domain/AAD identities or the installed agent before enforcing.',
    { allowed: [{ value: 0, label: 'Filtered token (secure)' }, { value: 1, label: 'Full token remotely' }],
      maps: { n171: ['3.1.5!', '3.1.12'], n53: ['AC-6!', 'AC-17'], soc2: ['CC6.3'] } }),

  // --- WinRM / WinRS ----------------------------------------------------
  wrm('at_winrm_client_no_basic', '18.10.89.1.1', 'WinRM Client: Disallow Basic authentication',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client', 'AllowBasic', 'REG_DWORD'], 0,
    'The WinRM client never uses Basic auth (credentials effectively in cleartext absent HTTPS).',
    'Scripts managing non-domain devices over WinRM with Basic+HTTPS (some appliance APIs) fail; switch them to certificate or negotiate auth.',
    { allowed: [{ value: 0, label: 'Basic blocked (secure)' }, { value: 1, label: 'Basic allowed' }],
      maps: { n171: ['3.5.10!', '3.1.12'], n53: ['IA-5!', 'AC-17'], hipaa: ['164.312(d)'], soc2: ['CC6.1'] } }),
  wrm('at_winrm_client_no_unencrypted', '18.10.89.1.2', 'WinRM Client: Disallow unencrypted traffic',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client', 'AllowUnencryptedTraffic', 'REG_DWORD'], 0,
    'WinRM client traffic must be encrypted (message-level or HTTPS).',
    'Connections to WinRM listeners explicitly configured unencrypted fail — fix the listener.',
    { allowed: [{ value: 0, label: 'Encryption required (secure)' }, { value: 1, label: 'Unencrypted allowed' }],
      maps: { n171: ['3.13.8!', '3.1.13'], n53: ['SC-8!', 'AC-17'], hipaa: ['164.312(e)(1)!'], soc2: ['CC6.7'] } }),
  wrm('at_winrm_client_no_digest', '18.10.89.1.3', 'WinRM Client: Disallow Digest authentication',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client', 'AllowDigest', 'REG_DWORD'], 0,
    'The WinRM client never uses Digest authentication (weak, replay-prone).',
    'Effectively none; Digest WinRM targets are museum pieces.',
    { allowed: [{ value: 0, label: 'Digest blocked (secure)' }, { value: 1, label: 'Digest allowed' }],
      maps: { n171: ['3.5.10'], n53: ['IA-5', 'AC-17'], soc2: ['CC6.1'] } }),
  wrm('at_winrm_service_no_basic', '18.10.89.2.1', 'WinRM Service: Disallow Basic authentication',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service', 'AllowBasic', 'REG_DWORD'], 0,
    'The WinRM service rejects inbound Basic authentication.',
    'Non-Windows automation (Ansible with basic auth over HTTPS, some monitoring) must switch to NTLM/Kerberos/certificate auth — Ansible supports all three.',
    { allowed: [{ value: 0, label: 'Basic blocked (secure)' }, { value: 1, label: 'Basic allowed' }],
      maps: { n171: ['3.5.10!', '3.1.12'], n53: ['IA-5!', 'AC-17'], hipaa: ['164.312(d)'], soc2: ['CC6.1'] } }),
  wrm('at_winrm_service_no_unencrypted', '18.10.89.2.3', 'WinRM Service: Disallow unencrypted traffic',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service', 'AllowUnencryptedTraffic', 'REG_DWORD'], 0,
    'The WinRM service rejects unencrypted inbound sessions.',
    'Management tools explicitly configured for unencrypted WinRM fail; fix the tool configuration.',
    { allowed: [{ value: 0, label: 'Encryption required (secure)' }, { value: 1, label: 'Unencrypted allowed' }],
      maps: { n171: ['3.13.8!'], n53: ['SC-8!', 'AC-17'], hipaa: ['164.312(e)(1)!'], soc2: ['CC6.7'] } }),
  wrm('at_winrm_service_no_runas', '18.10.89.2.4', 'WinRM Service: Disallow WinRM from storing RunAs credentials',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service', 'DisableRunAs', 'REG_DWORD'], 1,
    'WinRM plugins cannot store RunAs credentials on this host (stored secrets are dumpable).',
    'Custom WinRM plugin configurations using RunAs identities (rare; some JEA setups) must use virtual accounts instead.',
    { allowed: EN_DIS, maps: { n171: ['3.5.10!'], n53: ['IA-5!'], soc2: ['CC6.1'] } }),

  // --- Printers (PrintNightmare surface) --------------------------------
  prt('at_print_no_spooler_remote_rpc', '18.7.1', 'Allow Print Spooler to accept client connections: Disabled',
    ['SOFTWARE\\Policies\\Microsoft\\Windows NT\\Printers', 'RegisterSpoolerRemoteRpcEndPoint', 'REG_DWORD'], 2,
    'The Print Spooler stops accepting remote connections (2 = Disabled), removing this machine from the PrintNightmare remote-exploit surface. Local printing is unaffected.',
    'THIS MACHINE CANNOT SHARE PRINTERS while enforced. On actual print servers, exclude the machine or use a sub-policy — everywhere else it should be on.',
    { allowed: [{ value: 1, label: 'Remote connections allowed' }, { value: 2, label: 'Remote connections blocked (secure)' }],
      maps: { n171: ['3.4.6!', '3.13.1'], n53: ['CM-7!', 'SC-7'], soc2: ['CC6.6', 'CC7.1'] } }),
  prt('at_print_pnp_admin_only', '18.7.2', 'Point and Print: Restrict driver installation to administrators',
    ['SOFTWARE\\Policies\\Microsoft\\Windows NT\\Printers\\PointAndPrint', 'RestrictDriverInstallationToAdministrators', 'REG_DWORD'], 1,
    'Only administrators may install printer drivers via Point and Print (the post-PrintNightmare default, made explicit and drift-proof).',
    'Non-admin users connecting to a NEW shared printer needing a driver get blocked with an elevation request — pre-stage drivers via driver packages, or expect tickets.',
    { allowed: EN_DIS, maps: { n171: ['3.4.9!', '3.1.7'], n53: ['CM-11!', 'AC-6'], soc2: ['CC6.8'] } }),
  prt('at_print_pnp_install_warning', '18.7.3', 'Point and Print: Show warning and elevation prompt on install',
    ['SOFTWARE\\Policies\\Microsoft\\Windows NT\\Printers\\PointAndPrint', 'NoWarningNoElevationOnInstall', 'REG_DWORD'], 0,
    'Keep the warning/elevation prompt when installing a driver from a print server (0 = show).',
    'One extra elevation prompt during first-connect to a printer.',
    { allowed: [{ value: 0, label: 'Prompt (secure)' }, { value: 1, label: 'Silent install' }],
      maps: { n171: ['3.4.9'], n53: ['CM-11!'], soc2: ['CC6.8'] } }),
  prt('at_print_pnp_update_warning', '18.7.4', 'Point and Print: Show warning and elevation prompt on driver update',
    ['SOFTWARE\\Policies\\Microsoft\\Windows NT\\Printers\\PointAndPrint', 'UpdatePromptSettings', 'REG_DWORD'], 0,
    'Keep the warning/elevation prompt when an existing printer driver is updated from a server (0 = show).',
    'Same as the install prompt.',
    { allowed: [{ value: 0, label: 'Prompt (secure)' }, { value: 1, label: 'Silent on update' }, { value: 2, label: 'Silent always' }],
      maps: { n171: ['3.4.9'], n53: ['CM-11!'], soc2: ['CC6.8'] } }),

  // --- Credentials delegation / CredSSP ---------------------------------
  cred('at_credssp_encryption_oracle', '18.8.4.1', 'Encryption Oracle Remediation: Force Updated Clients',
    ['SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\CredSSP\\Parameters', 'AllowEncryptionOracle', 'REG_DWORD'], 0,
    'CredSSP (used by RDP) refuses connections with unpatched peers vulnerable to CVE-2018-0886 credential theft (0 = Force Updated Clients).',
    'RDP to machines unpatched since 2018 fails with a CredSSP error — patch the target rather than weakening this.',
    { allowed: [{ value: 0, label: 'Force updated clients (secure)' }, { value: 1, label: 'Mitigated' }, { value: 2, label: 'Vulnerable' }],
      maps: { n171: ['3.13.8', '3.14.1'], n53: ['SC-8', 'SI-2'], soc2: ['CC6.7'] } }),
  cred('at_cred_delegation_no_default', '18.8.4.2', 'Remote host allows delegation of non-exportable credentials',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\CredentialsDelegation', 'AllowProtectedCreds', 'REG_DWORD'], 1,
    'Enables Restricted Admin / Remote Credential Guard support so RDP can work WITHOUT leaving reusable credentials on the remote host.',
    'None — this enables the safer mode; clients opt in per connection.',
    { allowed: EN_DIS, maps: { n171: ['3.5.10', '3.1.12'], n53: ['IA-5', 'AC-17'], soc2: ['CC6.1'] } }),

  // --- Device Guard / Credential Guard ----------------------------------
  dg('at_dg_vbs_enable', '18.8.5.1', 'Turn On Virtualization Based Security',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\DeviceGuard', 'EnableVirtualizationBasedSecurity', 'REG_DWORD'], 1,
    'Enables VBS: the hypervisor isolates critical secrets and code-integrity decisions from the running OS.',
    'Requires 64-bit CPU virtualization extensions (and ideally UEFI+Secure Boot). On hosts running third-party hypervisors/VMs, enabling VBS can degrade or block nested virtualization; older drivers incompatible with HVCI can fail. Pilot on representative hardware first.',
    { allowed: EN_DIS, minBuild: 14393,
      maps: { n171: ['3.13.16', '3.5.10'], n53: ['SC-28', 'SI-16', 'IA-5'], soc2: ['CC6.1'] } }),
  dg('at_dg_platform_features', '18.8.5.2', 'Virtualization Based Protection: Secure Boot and DMA Protection',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\DeviceGuard', 'RequirePlatformSecurityFeatures', 'REG_DWORD'], 3,
    'Requires Secure Boot and DMA protection as the platform level for VBS (3 = Secure Boot + DMA).',
    'Machines without IOMMU/VT-d fall back or fail to start VBS; check hardware inventory.',
    { allowed: [{ value: 1, label: 'Secure Boot' }, { value: 3, label: 'Secure Boot + DMA (secure)' }], minBuild: 14393,
      maps: { n171: ['3.13.16'], n53: ['SC-28', 'SI-16'], soc2: ['CC6.1'] } }),
  dg('at_dg_credential_guard', '18.8.5.4', 'Credential Guard Configuration: Enabled with UEFI lock',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\DeviceGuard', 'LsaCfgFlags', 'REG_DWORD'], 1,
    'Runs LSA secrets inside VBS isolation (1 = enabled with UEFI lock) so even SYSTEM cannot read domain credentials from memory.',
    'BREAKS NTLMv1, unconstrained Kerberos delegation, and third-party SSO/VPN providers that read LSA secrets directly. UEFI lock means it cannot be turned off remotely — physical presence required. Enable only after piloting per tenant; not applicable to workgroup-only credential use.',
    { allowed: [{ value: 0, label: 'Disabled' }, { value: 1, label: 'Enabled with UEFI lock' }, { value: 2, label: 'Enabled without lock' }], minBuild: 14393,
      maps: { n171: ['3.5.10!'], n53: ['IA-5!', 'SC-28'], hipaa: ['164.312(a)(2)(iv)'], soc2: ['CC6.1'] } }),
  sys('at_elam_boot_policy', '18.8.14.1', 'Boot-Start Driver Initialization Policy: Good, unknown and bad but critical',
    ['SYSTEM\\CurrentControlSet\\Policies\\EarlyLaunch', 'DriverLoadPolicy', 'REG_DWORD'], 3,
    'Early-Launch Antimalware blocks boot-start drivers classified as bad (3 = allow good, unknown, bad-but-critical), stopping known-bad rootkit drivers before the OS is up.',
    'A driver misclassified as bad-and-not-critical fails to load at boot; extremely rare with WHQL drivers.',
    { allowed: [{ value: 1, label: 'Good and unknown' }, { value: 3, label: 'Good, unknown, bad-critical (secure)' }, { value: 7, label: 'All (off)' }],
      maps: { n171: ['3.14.2'], n53: ['SI-3', 'SI-7'], soc2: ['CC6.8'] } }),

  // --- Windows Defender Firewall (per profile) --------------------------
  ...(['Domain', 'Private', 'Public'] as const).flatMap((profile) => {
    const P = `SOFTWARE\\Policies\\Microsoft\\WindowsFirewall\\${profile}Profile`;
    const L = `${P}\\Logging`;
    const cisBase = { Domain: '9.1', Private: '9.2', Public: '9.3' }[profile];
    const lp = profile.toLowerCase();
    const profileRisk =
      profile === 'Public'
        ? 'Inbound block on the Public profile is the default posture; anything listening for inbound connections on untrusted networks should be reviewed, not allowed.'
        : 'Inbound-block breaks peer-to-peer services without explicit allow rules: file/printer sharing, remote management (RDP/WinRM/RMM), and scan-to-SMB targets all need inbound rules present. Windows ships defaults for the common ones; verify tenant-specific tools.';
    return [
      fw(`at_fw_${lp}_enable`, `${cisBase}.1`, `${profile} profile: Firewall state On`,
        [P, 'EnableFirewall', 'REG_DWORD'], 1,
        `Turns the firewall on for the ${profile} profile and prevents local tampering.`,
        'Firewall-replacing third-party suites that disable the Windows Firewall will fight this setting — standardize on Defender Firewall or exclude those machines.',
        { allowed: EN_DIS, maps: { n171: ['3.13.1!', '3.13.5'], n53: ['SC-7!'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.6!'] } }),
      fw(`at_fw_${lp}_inbound`, `${cisBase}.2`, `${profile} profile: Inbound connections Block (default)`,
        [P, 'DefaultInboundAction', 'REG_DWORD'], 1,
        `Inbound connections without a matching allow rule are blocked on the ${profile} profile.`,
        profileRisk,
        { allowed: [{ value: 1, label: 'Block (secure)' }, { value: 0, label: 'Allow' }],
          maps: { n171: ['3.13.1!', '3.13.6!'], n53: ['SC-7!'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.6!'] } }),
      fw(`at_fw_${lp}_notifications`, `${cisBase}.3`, `${profile} profile: Display a notification Off`,
        [P, 'DisableNotifications', 'REG_DWORD'], 1,
        'Suppresses the "Windows Firewall has blocked..." popups (users cannot meaningfully act on them).',
        'Users no longer see block notifications; ensure logging (below) is on so admins still can.',
        { allowed: EN_DIS, maps: { n53: ['SC-7'], soc2: ['CC6.6'] } }),
      fw(`at_fw_${lp}_logsize`, `${cisBase}.5`, `${profile} profile: Log file maximum size 16384 KB`,
        [L, 'LogFileSize', 'REG_DWORD'], 16384,
        'Firewall log capped at 16 MB so it holds useful history.',
        'None.',
        { maps: { n171: ['3.3.1'], n53: ['AU-4'], soc2: ['CC7.2'] } }),
      fw(`at_fw_${lp}_logdrops`, `${cisBase}.6`, `${profile} profile: Log dropped packets Yes`,
        [L, 'LogDroppedPackets', 'REG_DWORD'], 1,
        'Dropped inbound packets are written to the firewall log — evidence of scanning and blocked lateral movement.',
        'Log disk usage only.',
        { allowed: EN_DIS, maps: { n171: ['3.3.1', '3.14.6'], n53: ['AU-2', 'SI-4', 'SC-7'], soc2: ['CC7.2'] } }),
      fw(`at_fw_${lp}_logsuccess`, `${cisBase}.7`, `${profile} profile: Log successful connections Yes`,
        [L, 'LogSuccessfulConnections', 'REG_DWORD'], 1,
        'Allowed connections are logged too, completing the network picture for investigations.',
        'Log disk usage only.',
        { allowed: EN_DIS, maps: { n171: ['3.3.1', '3.14.6'], n53: ['AU-2', 'SI-4'], soc2: ['CC7.2'] } }),
    ];
  }),
];
