import { adminTemplate, EN_DIS, type SeedEntry } from '../types';

const DEF = 'Administrative Templates > Windows Components > Microsoft Defender Antivirus';
const ASR = 'Administrative Templates > Windows Components > Microsoft Defender Exploit Guard > Attack Surface Reduction';
const SS = 'Administrative Templates > Windows Components > File Explorer (SmartScreen)';
const WU = 'Administrative Templates > Windows Components > Windows Update';
const EL = 'Administrative Templates > Windows Components > Event Log Service';
const AP = 'Administrative Templates > Windows Components > AutoPlay Policies';
const RS = 'Administrative Templates > System > Removable Storage Access';
const MSI = 'Administrative Templates > Windows Components > Windows Installer';
const BL = 'Administrative Templates > Windows Components > BitLocker Drive Encryption';
const PS = 'Administrative Templates > Windows Components > Windows PowerShell';
const OFF = 'Administrative Templates > Microsoft Office > Security (Macros)';
const SCR = 'Administrative Templates > Control Panel > Personalization (Session Lock)';

const def = adminTemplate(DEF);
const asr = adminTemplate(ASR);
const ss = adminTemplate(SS);
const wu = adminTemplate(WU);
const el = adminTemplate(EL);
const ap = adminTemplate(AP);
const rs = adminTemplate(RS);
const msi = adminTemplate(MSI);
const bl = adminTemplate(BL);
const ps = adminTemplate(PS);
const off = adminTemplate(OFF);
const scr = adminTemplate(SCR);

const D = 'SOFTWARE\\Policies\\Microsoft\\Windows Defender';
const ASR_RULES = `${D}\\Windows Defender Exploit Guard\\ASR\\Rules`;
const AV_MAPS = { n171: ['3.14.2!', '3.14.4', '3.14.5'], n53: ['SI-3!'], hipaa: ['164.308(a)(5)(ii)(B)!'], soc2: ['CC6.8!'] };

/** One catalog entry per ASR rule (value name = rule GUID, "1" = block). */
const asrRule = (key: string, cis: string, guid: string, name: string, desc: string, risk: string): SeedEntry =>
  asr(key, cis, `ASR: ${name}`, [ASR_RULES, guid, 'REG_SZ'], '1', desc,
    risk || 'Run in Audit ("2") first per tenant and review Defender event 1121/1122 hits before switching to Block.',
    { allowed: [{ value: '1', label: 'Block' }, { value: '2', label: 'Audit' }, { value: '6', label: 'Warn' }, { value: '0', label: 'Off' }],
      maps: { n171: ['3.14.2!'], n53: ['SI-3!', 'CM-7'], hipaa: ['164.308(a)(5)(ii)(B)'], soc2: ['CC6.8!'] } });

export const adminTemplatesSystemEntries: SeedEntry[] = [
  // --- Microsoft Defender Antivirus ------------------------------------
  def('at_def_not_disabled', '18.10.43.1', 'Ensure Microsoft Defender Antivirus is not disabled',
    [D, 'DisableAntiSpyware', 'REG_DWORD'], 0,
    'Guarantees the built-in antivirus stays on (0 = not disabled). Defender auto-yields when a healthy third-party AV registers, so this is safe fleet-wide.',
    'None — with third-party AV installed, Defender goes passive by itself; this only prevents malicious/manual disabling.',
    { allowed: [{ value: 0, label: 'Defender allowed to run (secure)' }, { value: 1, label: 'Defender disabled' }], maps: AV_MAPS }),
  def('at_def_realtime', '18.10.43.10.2', 'Real-time protection: Do not disable',
    [`${D}\\Real-Time Protection`, 'DisableRealtimeMonitoring', 'REG_DWORD'], 0,
    'Keeps on-access scanning enabled (0 = monitoring on).',
    'Heavy build/database servers sometimes exclude paths for performance — use exclusions, never a global off.',
    { allowed: [{ value: 0, label: 'Real-time on (secure)' }, { value: 1, label: 'Real-time off' }], maps: AV_MAPS }),
  def('at_def_behavior_monitoring', '18.10.43.10.1', 'Real-time protection: Behavior monitoring on',
    [`${D}\\Real-Time Protection`, 'DisableBehaviorMonitoring', 'REG_DWORD'], 0,
    'Behavioral detection of suspicious process activity stays enabled.',
    'None meaningful.',
    { allowed: [{ value: 0, label: 'On (secure)' }, { value: 1, label: 'Off' }], maps: AV_MAPS }),
  def('at_def_ioav', '18.10.43.10.3', 'Real-time protection: Scan all downloaded files and attachments',
    [`${D}\\Real-Time Protection`, 'DisableIOAVProtection', 'REG_DWORD'], 0,
    'Downloads and attachments are scanned on arrival.',
    'None meaningful.',
    { allowed: [{ value: 0, label: 'On (secure)' }, { value: 1, label: 'Off' }], maps: AV_MAPS }),
  def('at_def_script_scanning', '18.10.43.10.4', 'Real-time protection: Script scanning on',
    [`${D}\\Real-Time Protection`, 'DisableScriptScanning', 'REG_DWORD'], 0,
    'AMSI-integrated scanning of scripts (PowerShell, JScript, VBScript) stays enabled.',
    'None meaningful.',
    { allowed: [{ value: 0, label: 'On (secure)' }, { value: 1, label: 'Off' }], maps: AV_MAPS }),
  def('at_def_removable_scan', '18.10.43.13.1', 'Scan removable drives',
    [`${D}\\Scan`, 'DisableRemovableDriveScanning', 'REG_DWORD'], 0,
    'Full scans include removable drives (0 = scan them); pairs with the removable-storage and USB-ASR controls.',
    'Longer scans when large external drives are attached.',
    { allowed: [{ value: 0, label: 'Scan removable (secure)' }, { value: 1, label: 'Skip removable' }],
      maps: { ...AV_MAPS, n171: ['3.14.2!', '3.8.1'], n53: ['SI-3!', 'MP-7'] } }),
  def('at_def_email_scan', '18.10.43.13.2', 'Turn on e-mail scanning',
    [`${D}\\Scan`, 'DisableEmailScanning', 'REG_DWORD'], 0,
    'Mailbox-file and attachment parsing during scans (0 = scan email stores).',
    'Slightly longer scans on machines with huge PST archives.',
    { allowed: [{ value: 0, label: 'Scan email (secure)' }, { value: 1, label: 'Skip email' }], maps: AV_MAPS }),
  def('at_def_sigcheck_before_scan', '18.10.43.13.3', 'Check for signatures before running scan',
    [`${D}\\Scan`, 'CheckForSignaturesBeforeRunningScan', 'REG_DWORD'], 1,
    'Pull fresh definitions before each scheduled scan.',
    'None.',
    { allowed: EN_DIS, maps: { ...AV_MAPS, n171: ['3.14.4!'], n53: ['SI-3!'] } }),
  def('at_def_maps_join', '18.10.43.5.1', 'MAPS: Join Microsoft MAPS (Advanced)',
    [`${D}\\Spynet`, 'SpynetReporting', 'REG_DWORD'], 2,
    'Cloud-delivered protection membership (2 = Advanced MAPS) — required for cloud block-at-first-sight verdicts.',
    'Sends threat telemetry (file metadata, some samples per the consent setting) to Microsoft — flag to privacy-sensitive tenants.',
    { allowed: [{ value: 0, label: 'Off' }, { value: 1, label: 'Basic' }, { value: 2, label: 'Advanced (secure)' }], maps: AV_MAPS }),
  def('at_def_sample_consent', '18.10.43.5.2', 'MAPS: Send file samples when further analysis is required (safe samples)',
    [`${D}\\Spynet`, 'SubmitSamplesConsent', 'REG_DWORD'], 1,
    'Automatically submit non-personal executable samples for cloud analysis (1 = safe samples).',
    'Documents are never auto-submitted at this level; still worth flagging under data-handling policies.',
    { allowed: [{ value: 0, label: 'Always prompt' }, { value: 1, label: 'Safe samples (secure)' }, { value: 2, label: 'Never send' }, { value: 3, label: 'All samples' }], maps: AV_MAPS }),
  def('at_def_cloud_block_level', '18.10.43.6.1', 'MpEngine: Cloud protection level High',
    [`${D}\\MpEngine`, 'MpCloudBlockLevel', 'REG_DWORD'], 2,
    'More aggressive cloud heuristics (2 = High) — blocks unknowns at higher suspicion levels.',
    'Slightly higher false-positive rate on rare/unsigned line-of-business binaries; add publisher exclusions for known-good LOB apps.',
    { allowed: [{ value: 0, label: 'Default' }, { value: 2, label: 'High (secure)' }, { value: 4, label: 'High+' }, { value: 6, label: 'Zero tolerance' }], maps: AV_MAPS }),
  def('at_def_cloud_timeout', '18.10.43.6.2', 'MpEngine: Extended cloud check timeout (50s)',
    [`${D}\\MpEngine`, 'MpBafsExtendedTimeout', 'REG_DWORD'], 50,
    'Wait up to 50 extra seconds for a cloud verdict before releasing a suspicious file.',
    'First launch of an unknown binary can pause up to ~60s while the cloud decides.',
    { maps: AV_MAPS }),
  def('at_def_pua', '18.10.43.16', 'PUA protection: Block potentially unwanted applications',
    [D, 'PUAProtection', 'REG_DWORD'], 1,
    'Blocks bundlers, ad-injectors, crypto-miners, and other PUA-class software.',
    'Some "free utility" installers users like (download managers, toolbars) get blocked — that is the point, but expect the occasional ticket.',
    { allowed: [{ value: 0, label: 'Off' }, { value: 1, label: 'Block (secure)' }, { value: 2, label: 'Audit' }], maps: AV_MAPS }),
  def('at_def_network_protection', '18.10.43.7.1', 'Network protection: Block dangerous domains',
    [`${D}\\Windows Defender Exploit Guard\\Network Protection`, 'EnableNetworkProtection', 'REG_DWORD'], 1,
    'Blocks outbound connections to known-malicious hosts from ANY process (SmartScreen for the whole OS).',
    'Rare false positives on niche business sites; start in Audit (2) for cautious tenants, then Block.',
    { allowed: [{ value: 0, label: 'Off' }, { value: 1, label: 'Block (secure)' }, { value: 2, label: 'Audit' }],
      maps: { ...AV_MAPS, n171: ['3.14.2!', '3.13.1'], n53: ['SI-3!', 'SC-7'] } }),
  def('at_def_local_admin_merge', '18.10.43.4', 'Local admin merge for lists: Disabled',
    [D, 'DisableLocalAdminMerge', 'REG_DWORD'], 1,
    'Local exclusion/threat lists are ignored in favor of policy (1 = local merge off) so malware running as admin cannot self-exclude.',
    'Machine-specific AV exclusions must move into policy — local ones stop applying.',
    { allowed: [{ value: 1, label: 'Local lists ignored (secure)' }, { value: 0, label: 'Local lists merged' }], maps: AV_MAPS }),

  // --- ASR rules --------------------------------------------------------
  asr('at_asr_enable', '18.10.43.6.1.1', 'Configure Attack Surface Reduction rules: Enabled',
    [`${D}\\Windows Defender Exploit Guard\\ASR`, 'ExploitGuard_ASR_Rules', 'REG_DWORD'], 1,
    'Master switch that makes the per-rule ASR settings below take effect.',
    'None by itself; per-rule impact listed on each rule.',
    { allowed: EN_DIS, maps: { n171: ['3.14.2!'], n53: ['SI-3!', 'CM-7'], hipaa: ['164.308(a)(5)(ii)(B)'], soc2: ['CC6.8!'] } }),
  asrRule('at_asr_vuln_drivers', '18.10.43.6.1.2', '56a863a9-875e-4185-98a7-b882c64b5ce5', 'Block abuse of exploited vulnerable signed drivers',
    'Stops known-vulnerable signed drivers from being written to disk (BYOVD kernel attacks).',
    'Rare hits on legacy hardware utilities and overclocking/fan tools that ship old drivers.'),
  asrRule('at_asr_adobe_child', '18.10.43.6.1.3', '7674ba52-37eb-4a4f-a9a1-f0f9a1619a2c', 'Block Adobe Reader from creating child processes',
    'PDF exploit payloads cannot spawn processes from Reader.',
    'Some Reader plugins/print workflows launch helpers; audit first where Reader is heavily customized.'),
  asrRule('at_asr_office_child', '18.10.43.6.1.4', 'd4f940ab-401b-4efc-aadc-ad5f3c50688a', 'Block all Office applications from creating child processes',
    'Macro payloads cannot launch cmd/powershell/wscript from Office.',
    'Office add-ins that spawn helper processes (some finance/ERP add-ins, mail-merge tooling) break — audit per tenant before block.'),
  asrRule('at_asr_lsass_steal', '18.10.43.6.1.5', '9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2', 'Block credential stealing from LSASS',
    'Blocks unexpected reads of LSASS memory (Mimikatz-class) even where LSA protection is off.',
    'Some legacy SSO agents and password managers read LSASS — audit hits before enforcing; those apps need updating regardless.'),
  asrRule('at_asr_email_exec', '18.10.43.6.1.6', 'be9ba2d9-53ea-4cdc-84e5-9b1eeee46550', 'Block executable content from email client and webmail',
    'Executables saved/launched directly out of mail clients are blocked.',
    'Users emailing themselves tools/installers must save-then-run from disk instead.'),
  asrRule('at_asr_exec_criteria', '18.10.43.6.1.7', '01443614-cd74-433a-b99e-2ecdc07bfc25', 'Block executables unless they meet prevalence, age, or trusted-list criteria',
    'Unknown, brand-new binaries are blocked until they earn reputation.',
    'HIGH friction for software shops and niche LOB apps (self-built tools are always "unknown"). Audit first; use exclusions for build outputs.'),
  asrRule('at_asr_obfuscated', '18.10.43.6.1.8', '5beb7efe-fd9a-4556-801d-275e5ffc04cc', 'Block execution of potentially obfuscated scripts',
    'Heuristic block of packed/obfuscated PowerShell/JS/VBS.',
    'Some vendor installers and minified admin scripts trip it; audit hits before block.'),
  asrRule('at_asr_js_vbs_exec', '18.10.43.6.1.9', 'd3e037e1-3eb8-44c8-a917-57927947596d', 'Block JavaScript or VBScript from launching downloaded executable content',
    'Script-chain droppers (js -> exe) are cut at the launch step.',
    'Rare legitimate use; near-zero business impact.'),
  asrRule('at_asr_office_exec_content', '18.10.43.6.1.10', '3b576869-a4ec-4529-8536-b80a7769e899', 'Block Office applications from creating executable content',
    'Office cannot write executable files/scripts to disk (macro dropper pattern).',
    'Macro-driven exports that generate scripts break; audit in macro-heavy finance/logistics tenants.'),
  asrRule('at_asr_office_inject', '18.10.43.6.1.11', '75668c1f-73b5-4cf0-bb93-3ecf5cb7cc84', 'Block Office applications from injecting code into other processes',
    'Office processes cannot inject into other processes (post-exploit hollowing pattern).',
    'A few legacy add-ins do injection-like tricks; audit first.'),
  asrRule('at_asr_office_comm_child', '18.10.43.6.1.12', '26190899-1602-49e8-8b27-eb1d0a1ce869', 'Block Office communication application from creating child processes',
    'Outlook cannot spawn processes (mail-borne exploit chain cut).',
    'Outlook add-ins that launch helpers (CRM dialers, meeting tools) may trip — audit where such add-ins exist.'),
  asrRule('at_asr_wmi_persist', '18.10.43.6.1.13', 'e6db77e5-3df2-4cf1-b95a-636979351e5b', 'Block persistence through WMI event subscription',
    'Fileless persistence via WMI event subscriptions is blocked.',
    'Some enterprise management suites (SCCM-adjacent tooling) legitimately use WMI subscriptions — audit hits first.'),
  asrRule('at_asr_psexec_wmi', '18.10.43.6.1.14', 'd1e49aac-8f56-4280-b9ba-993a6d77406c', 'Block process creations originating from PSExec and WMI commands',
    'Lateral-movement execution via PsExec/WMI is blocked at the child-process step.',
    'CONFLICTS with SCCM/ConfigMgr client push and admin scripts that rely on WMI process creation, and with PsExec-based tooling. Audit carefully; many MSP stacks need this in Audit rather than Block.'),
  asrRule('at_asr_usb_untrusted', '18.10.43.6.1.15', 'b2b3f03d-6a65-4f7b-a9c7-1c7ef74a9ba4', 'Block untrusted and unsigned processes that run from USB',
    'Unsigned executables on removable media cannot run.',
    'Vendor field-service USB tools that are unsigned get blocked — copy to disk first or sign them.'),
  asrRule('at_asr_office_macro_win32', '18.10.43.6.1.16', '92e97fa1-2edf-4476-bdd6-9dd0b4dddc7b', 'Block Win32 API calls from Office macros',
    'VBA macros cannot call Win32 APIs (shellcode-in-macro pattern).',
    'Sophisticated legitimate macro apps using Declare statements break — common in old actuarial/engineering spreadsheets; audit per tenant.'),
  asrRule('at_asr_ransomware', '18.10.43.6.1.17', 'c1db55ab-c21a-4637-bb3f-a12568109d35', 'Use advanced protection against ransomware',
    'Cloud-backed behavioral shield specifically tuned for ransomware encryption behavior.',
    'Backup/sync tools that rewrite many files quickly can trip it; audit hits, exclude the tool, then block.'),
  asrRule('at_asr_safe_mode_reboot', '18.10.43.6.1.18', '33ddedf1-c6e0-47cb-833e-de6133960387', 'Block rebooting machine in Safe Mode',
    'Blocks the ransomware trick of rebooting into Safe Mode where AV is off.',
    'Technicians using scripted Safe Mode boots for repair must do it from recovery media instead.'),

  // --- SmartScreen ------------------------------------------------------
  ss('at_smartscreen_explorer', '18.10.44.1', 'Configure Windows Defender SmartScreen: Warn and prevent bypass',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\System', 'EnableSmartScreen', 'REG_DWORD'], 1,
    'SmartScreen reputation-checks downloaded programs before they run.',
    'Unsigned niche installers show warnings users cannot bypass (with the level below) — distribute LOB software through managed installs.',
    { allowed: EN_DIS, maps: { n171: ['3.14.2!'], n53: ['SI-3!'], hipaa: ['164.308(a)(5)(ii)(B)'], soc2: ['CC6.8!'] } }),
  ss('at_smartscreen_level', '18.10.44.2', 'SmartScreen level: Block',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\System', 'ShellSmartScreenLevel', 'REG_SZ'], 'Block',
    'Sets SmartScreen to Block (no user bypass) rather than Warn.',
    'See the SmartScreen enable setting — no bypass means helpdesk handles every legitimate unknown binary.',
    { allowed: [{ value: 'Block', label: 'Block (secure)' }, { value: 'Warn', label: 'Warn' }],
      maps: { n171: ['3.14.2!'], n53: ['SI-3!'], soc2: ['CC6.8!'] } }),

  // --- Windows Update ---------------------------------------------------
  wu('at_wu_no_auto_update_off', '18.10.92.2.1', 'Configure Automatic Updates: Enabled',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU', 'NoAutoUpdate', 'REG_DWORD'], 0,
    'Automatic Updates stays enabled (0 = auto update on).',
    'Update installs can reboot machines outside maintenance windows unless scheduling (below) is set thoughtfully.',
    { allowed: [{ value: 0, label: 'Auto update on (secure)' }, { value: 1, label: 'Auto update off' }],
      maps: { n171: ['3.14.1!'], n53: ['SI-2!'], hipaa: ['164.308(a)(5)(ii)(B)'], soc2: ['CC7.1!'] } }),
  wu('at_wu_auoptions', '18.10.92.2.2', 'Automatic Updates: Auto download and schedule the install',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU', 'AUOptions', 'REG_DWORD'], 4,
    'Updates download automatically and install on the configured schedule (4).',
    'Combined with the scheduled day/time below; servers should get maintenance-window sub-policies.',
    { allowed: [{ value: 2, label: 'Notify download' }, { value: 3, label: 'Auto download, notify install' }, { value: 4, label: 'Auto download + schedule (secure)' }, { value: 5, label: 'Local admin chooses' }],
      maps: { n171: ['3.14.1!'], n53: ['SI-2!'], soc2: ['CC7.1'] } }),
  wu('at_wu_scheduled_day', '18.10.92.2.3', 'Automatic Updates: Scheduled install day (Every day)',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU', 'ScheduledInstallDay', 'REG_DWORD'], 0,
    'Install updates every day (0) at the scheduled time.',
    'None beyond reboot timing.',
    { maps: { n171: ['3.14.1'], n53: ['SI-2!'], soc2: ['CC7.1'] } }),
  wu('at_wu_no_reboot_with_users', '18.10.92.2.4', 'No auto-restart with logged on users: Disabled',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU', 'NoAutoRebootWithLoggedOnUsers', 'REG_DWORD'], 0,
    'Updates are allowed to schedule restarts even when users are signed in (0 = allowed, with normal restart-notification UX).',
    'Users get restart prompts/deadlines — pair with organizational comms; kiosk machines may reboot mid-display.',
    { allowed: [{ value: 0, label: 'Scheduled restarts proceed (secure)' }, { value: 1, label: 'Never restart with users on' }],
      maps: { n171: ['3.14.1'], n53: ['SI-2!'], soc2: ['CC7.1'] } }),
  wu('at_wu_no_preview_builds', '18.10.92.4.1', 'Manage preview builds: Disable preview builds',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate', 'ManagePreviewBuilds', 'REG_DWORD'], 1,
    'Blocks enrolling production machines into Insider preview builds (paired value below).',
    'None on production fleets.',
    { allowed: EN_DIS, maps: { n171: ['3.4.2'], n53: ['CM-6', 'SI-2'], soc2: ['CC7.1'] } }),
  wu('at_wu_preview_builds_value', '18.10.92.4.2', 'Manage preview builds: policy value Disabled',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate', 'ManagePreviewBuildsPolicyValue', 'REG_DWORD'], 0,
    'Companion value for the preview-builds policy (0 = disabled).',
    'None.',
    { maps: { n171: ['3.4.2'], n53: ['CM-6'], soc2: ['CC7.1'] } }),
  wu('at_wu_quality_defer', '18.10.92.4.3', 'Quality updates: not deferred',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate', 'DeferQualityUpdates', 'REG_DWORD'], 1,
    'Quality-update deferral policy is set explicitly with 0 days (see companion), keeping patches immediate but policy-controlled.',
    'None — 0-day deferral means patches land as released.',
    { allowed: EN_DIS, maps: { n171: ['3.14.1!'], n53: ['SI-2!'], soc2: ['CC7.1'] } }),
  wu('at_wu_quality_defer_days', '18.10.92.4.4', 'Quality updates deferral days: 0',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate', 'DeferQualityUpdatesPeriodInDays', 'REG_DWORD'], 0,
    'Companion value: defer quality updates 0 days.',
    'None.',
    { maps: { n171: ['3.14.1!'], n53: ['SI-2!'], soc2: ['CC7.1'] } }),

  // --- Event Log sizes --------------------------------------------------
  el('at_el_app_maxsize', '18.10.25.1.2', 'Application log: Maximum size 32768 KB or greater',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\EventLog\\Application', 'MaxSize', 'REG_DWORD'], 32768,
    'Application log holds at least 32 MB so troubleshooting history survives.',
    'Disk usage only.',
    { maps: { n171: ['3.3.1'], n53: ['AU-4!'], hipaa: ['164.312(b)'], soc2: ['CC7.2'] } }),
  el('at_el_app_retention', '18.10.25.1.1', 'Application log: Overwrite as needed',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\EventLog\\Application', 'Retention', 'REG_SZ'], '0',
    'Oldest events are overwritten when full ("0") instead of halting logging.',
    'Very old events roll off — ship logs to a collector if long retention is required.',
    { maps: { n171: ['3.3.1'], n53: ['AU-4'], soc2: ['CC7.2'] } }),
  el('at_el_sec_maxsize', '18.10.25.2.2', 'Security log: Maximum size 196608 KB or greater',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\EventLog\\Security', 'MaxSize', 'REG_DWORD'], 196608,
    'Security log holds at least 192 MB — the audit policy above is worthless if the log wraps hourly.',
    'Disk usage only (~200 MB).',
    { maps: { n171: ['3.3.1!', '3.3.8'], n53: ['AU-4!', 'AU-9'], hipaa: ['164.312(b)!'], soc2: ['CC7.2!'] } }),
  el('at_el_sec_retention', '18.10.25.2.1', 'Security log: Overwrite as needed',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\EventLog\\Security', 'Retention', 'REG_SZ'], '0',
    'Oldest security events are overwritten when full rather than freezing auditing.',
    'Forensic depth bounded by log size; use a SIEM for retention.',
    { maps: { n171: ['3.3.1'], n53: ['AU-4'], soc2: ['CC7.2'] } }),
  el('at_el_sys_maxsize', '18.10.25.4.2', 'System log: Maximum size 32768 KB or greater',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\EventLog\\System', 'MaxSize', 'REG_DWORD'], 32768,
    'System log holds at least 32 MB.',
    'Disk usage only.',
    { maps: { n171: ['3.3.1'], n53: ['AU-4!'], soc2: ['CC7.2'] } }),
  el('at_el_sys_retention', '18.10.25.4.1', 'System log: Overwrite as needed',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\EventLog\\System', 'Retention', 'REG_SZ'], '0',
    'Oldest events are overwritten when full.',
    'See Application log.',
    { maps: { n171: ['3.3.1'], n53: ['AU-4'], soc2: ['CC7.2'] } }),
  el('at_el_cmdline_in_4688', '18.9.3.1', 'Include command line in process creation events',
    ['SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\Audit', 'ProcessCreationIncludeCmdLine_Enabled', 'REG_DWORD'], 1,
    'Event 4688 records the full command line — turns process auditing from names into actual behavior.',
    'Command lines can contain secrets passed as arguments (a practice to eliminate anyway); the log is admin-readable only.',
    { allowed: EN_DIS, maps: { n171: ['3.3.1!', '3.3.2'], n53: ['AU-3!', 'AU-2'], hipaa: ['164.312(b)'], soc2: ['CC7.2!'] } }),

  // --- AutoPlay / removable storage ------------------------------------
  ap('at_ap_no_autoplay', '18.10.7.1', 'Turn off Autoplay on all drives',
    ['SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer', 'NoDriveTypeAutoRun', 'REG_DWORD'], 255,
    'Autoplay is disabled for every drive type (255) — plugging in a USB stick never auto-launches anything.',
    'Users must open removable media manually; none beyond that.',
    { maps: { n171: ['3.8.7!', '3.14.2'], n53: ['MP-7!', 'SI-3'], hipaa: ['164.310(d)(1)'], soc2: ['CC6.8'] } }),
  ap('at_ap_no_autorun_cmd', '18.10.7.2', 'Set the default behavior for AutoRun: Do not execute',
    ['SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer', 'NoAutorun', 'REG_DWORD'], 1,
    'autorun.inf commands never execute (1 = do not execute).',
    'None on modern systems.',
    { allowed: EN_DIS, maps: { n171: ['3.8.7!'], n53: ['MP-7!', 'SI-3'], soc2: ['CC6.8'] } }),
  ap('at_ap_no_autoplay_nonvolume', '18.10.7.3', 'Disallow Autoplay for non-volume devices',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\Explorer', 'NoAutoplayfornonVolume', 'REG_DWORD'], 1,
    'MTP devices (cameras, phones) do not autoplay either.',
    'None.',
    { allowed: EN_DIS, maps: { n171: ['3.8.7!'], n53: ['MP-7!'], soc2: ['CC6.8'] } }),
  rs('at_rs_deny_all', '18.8.7.2', 'All Removable Storage classes: Deny all access',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\RemovableStorageDevices', 'Deny_All', 'REG_DWORD'], 0,
    'Master kill switch for ALL removable storage (USB drives, optical, portable devices). Baseline default is 0 (allowed) — enable per tenant/policy where data-exfiltration risk dominates.',
    'When enabled, USB drives simply do not mount: field engineers, backup-to-USB jobs, and dongle-adjacent tools all stop. High-security tenants only, with a communicated exception process.',
    { allowed: [{ value: 0, label: 'Allowed' }, { value: 1, label: 'All removable storage denied' }],
      maps: { n171: ['3.8.1', '3.8.7!', '3.1.21!'], n53: ['MP-7!'], hipaa: ['164.310(d)(1)!'], soc2: ['CC6.7'] },
      recommended: { hipaa: 1, cmmc: 1, nist_800_171: 1 } }),
  rs('at_rs_disk_deny_write', '18.8.7.1', 'Removable Disks: Deny write access',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\RemovableStorageDevices\\{53f5630d-b6bf-11d0-94f2-00a0c91efb8b}', 'Deny_Write', 'REG_DWORD'], 0,
    'Removable disks become read-only: data can be brought in but not carried out. Baseline default 0; recommended 1 for frameworks with media-protection controls.',
    'Writing to USB drives stops — scan-to-USB on copiers, technician imaging sticks, and ad-hoc file handoffs all break. Read access continues to work.',
    { allowed: [{ value: 0, label: 'Write allowed' }, { value: 1, label: 'Write denied' }],
      maps: { n171: ['3.8.1!', '3.1.21!'], n53: ['MP-7!'], hipaa: ['164.310(d)(1)!', '164.312(a)(2)(iv)?'], soc2: ['CC6.7'] },
      recommended: { hipaa: 1, cmmc: 1, nist_800_171: 1 } }),

  // --- Windows Installer ------------------------------------------------
  msi('at_msi_always_elevated', '18.10.90.2', 'Always install with elevated privileges: Disabled',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\Installer', 'AlwaysInstallElevated', 'REG_DWORD'], 0,
    'MSI packages never auto-elevate to SYSTEM for standard users (0). Enabled is an instant local-privilege-escalation hole.',
    'None — enabling it was always the misconfiguration.',
    { allowed: [{ value: 0, label: 'Disabled (secure)' }, { value: 1, label: 'Enabled (dangerous)' }],
      maps: { n171: ['3.1.7!', '3.4.9'], n53: ['AC-6!', 'CM-11'], soc2: ['CC6.3'] } }),
  msi('at_msi_user_control_off', '18.10.90.1', 'Allow user control over installs: Disabled',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\Installer', 'EnableUserControl', 'REG_DWORD'], 0,
    'Users cannot change install paths/options that installers marked restricted.',
    'None for normal software.',
    { allowed: [{ value: 0, label: 'Disabled (secure)' }, { value: 1, label: 'Enabled' }],
      maps: { n171: ['3.4.9'], n53: ['CM-11!'], soc2: ['CC6.8'] } }),

  // --- BitLocker (core) -------------------------------------------------
  bl('at_bl_os_encryption_method', '18.10.9.1', 'BitLocker OS drive: encryption method XTS-AES 256',
    ['SOFTWARE\\Policies\\Microsoft\\FVE', 'EncryptionMethodWithXtsOs', 'REG_DWORD'], 7,
    'New OS-drive BitLocker volumes use XTS-AES 256 (7).',
    'Applies to NEW encryptions only — already-encrypted drives keep their method until re-encrypted. Requires TPM-capable hardware for sensible deployment.',
    { allowed: [{ value: 3, label: 'AES-CBC 128' }, { value: 4, label: 'AES-CBC 256' }, { value: 6, label: 'XTS-AES 128' }, { value: 7, label: 'XTS-AES 256 (secure)' }],
      maps: { n171: ['3.13.16!', '3.13.11'], n53: ['SC-28!', 'SC-13'], hipaa: ['164.312(a)(2)(iv)!', '164.310(d)(1)'], soc2: ['CC6.7'] } }),
  bl('at_bl_fixed_encryption_method', '18.10.9.2', 'BitLocker fixed drives: encryption method XTS-AES 256',
    ['SOFTWARE\\Policies\\Microsoft\\FVE', 'EncryptionMethodWithXtsFdv', 'REG_DWORD'], 7,
    'New fixed-data-drive volumes use XTS-AES 256.',
    'Same as the OS-drive method setting.',
    { allowed: [{ value: 3, label: 'AES-CBC 128' }, { value: 4, label: 'AES-CBC 256' }, { value: 6, label: 'XTS-AES 128' }, { value: 7, label: 'XTS-AES 256 (secure)' }],
      maps: { n171: ['3.13.16!'], n53: ['SC-28!'], hipaa: ['164.312(a)(2)(iv)!'], soc2: ['CC6.7'] } }),
  bl('at_bl_removable_encryption_method', '18.10.9.3', 'BitLocker removable drives: encryption method AES-CBC 256',
    ['SOFTWARE\\Policies\\Microsoft\\FVE', 'EncryptionMethodWithXtsRdv', 'REG_DWORD'], 4,
    'BitLocker To Go uses AES-CBC 256 (4) for cross-machine compatibility.',
    'Same as the OS-drive method setting.',
    { allowed: [{ value: 3, label: 'AES-CBC 128' }, { value: 4, label: 'AES-CBC 256 (secure)' }, { value: 6, label: 'XTS-AES 128' }, { value: 7, label: 'XTS-AES 256' }],
      maps: { n171: ['3.8.1', '3.13.16'], n53: ['SC-28!', 'MP-7'], hipaa: ['164.312(a)(2)(iv)!', '164.310(d)(1)'], soc2: ['CC6.7'] } }),
  bl('at_bl_deny_unprotected_removable', '18.10.9.4', 'Deny write access to removable drives not protected by BitLocker',
    ['SOFTWARE\\Policies\\Microsoft\\FVE', 'RDVDenyWriteAccess', 'REG_DWORD'], 0,
    'Unencrypted USB drives become read-only; users can only write to BitLocker-protected sticks. Baseline default 0; recommended 1 for HIPAA/CMMC tenants.',
    'Every non-BitLocker USB stick in the tenant becomes read-only on write attempts — plan a supply of encrypted drives and user comms before enabling.',
    { allowed: [{ value: 0, label: 'Writes allowed' }, { value: 1, label: 'Unprotected drives read-only' }],
      maps: { n171: ['3.8.1!', '3.1.21'], n53: ['MP-7!', 'SC-28'], hipaa: ['164.312(a)(2)(iv)!', '164.310(d)(1)!'], soc2: ['CC6.7'] },
      recommended: { hipaa: 1, cmmc: 1 } }),

  // --- PowerShell logging ----------------------------------------------
  ps('at_ps_scriptblock_logging', '18.10.87.1', 'Turn on PowerShell Script Block Logging',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging', 'EnableScriptBlockLogging', 'REG_DWORD'], 1,
    'Logs the content of every executed script block (event 4104), including de-obfuscated payloads — the highest-value PowerShell telemetry.',
    'Log volume; secrets hardcoded in scripts land in the event log (readable by admins). Fix the scripts.',
    { allowed: EN_DIS, maps: { n171: ['3.3.1!', '3.3.2'], n53: ['AU-2!', 'AU-3', 'AU-12!'], hipaa: ['164.312(b)!'], soc2: ['CC7.2!'] } }),
  ps('at_ps_module_logging', '18.10.87.2', 'Turn on Module Logging',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ModuleLogging', 'EnableModuleLogging', 'REG_DWORD'], 1,
    'Logs pipeline execution events per module (event 4103), complementing script-block logging.',
    'Meaningful log volume on automation-heavy hosts.',
    { allowed: EN_DIS, maps: { n171: ['3.3.1!'], n53: ['AU-2!', 'AU-12'], hipaa: ['164.312(b)'], soc2: ['CC7.2'] } }),
  ps('at_ps_module_names', '18.10.87.3', 'Module Logging: log all modules (*)',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ModuleLogging\\ModuleNames', '*', 'REG_SZ'], '*',
    'Companion list for module logging: "*" logs every module.',
    'None beyond volume.',
    { maps: { n171: ['3.3.1'], n53: ['AU-12'], soc2: ['CC7.2'] } }),
  ps('at_ps_transcription', '18.10.87.4', 'Turn on PowerShell Transcription',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\Transcription', 'EnableTranscripting', 'REG_DWORD'], 1,
    'Writes full session transcripts (commands + output) to text files for every PowerShell session.',
    'Transcripts capture OUTPUT, which can include sensitive query results — point OutputDirectory at a protected path and mind retention. Disk usage on automation hosts.',
    { allowed: EN_DIS, maps: { n171: ['3.3.1!'], n53: ['AU-2!', 'AU-3!'], hipaa: ['164.312(b)'], soc2: ['CC7.2'] } }),
  ps('at_ps_transcription_invocation', '18.10.87.5', 'Transcription: include invocation headers',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\Transcription', 'EnableInvocationHeader', 'REG_DWORD'], 1,
    'Adds per-command timestamps to transcripts.',
    'None.',
    { allowed: EN_DIS, maps: { n171: ['3.3.1'], n53: ['AU-3!', 'AU-8'], soc2: ['CC7.2'] } }),
  ps('at_ps_execution_policy', '18.10.87.6', 'Turn on Script Execution: Allow only signed or RemoteSigned scripts',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell', 'EnableScripts', 'REG_DWORD'], 1,
    'Policy-enforces script execution with the companion ExecutionPolicy value (RemoteSigned): downloaded scripts must be signed.',
    'Execution policy is a guardrail, not a security boundary (trivially bypassed by design) — treat as hygiene. Unsigned scripts downloaded from the internet stop running until unblocked/signed.',
    { allowed: EN_DIS, maps: { n171: ['3.4.8?'], n53: ['CM-7?'], soc2: ['CC6.8'] } }),
  ps('at_ps_execution_policy_value', '18.10.87.7', 'Script Execution policy value: RemoteSigned',
    ['SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell', 'ExecutionPolicy', 'REG_SZ'], 'RemoteSigned',
    'Companion value for Turn on Script Execution.',
    'See Turn on Script Execution.',
    { allowed: [{ value: 'AllSigned', label: 'AllSigned' }, { value: 'RemoteSigned', label: 'RemoteSigned (recommended)' }],
      maps: { n171: ['3.4.8?'], n53: ['CM-7?'], soc2: ['CC6.8'] } }),

  // --- Office macro surface (per-user policy) ---------------------------
  off('at_office_macro_block_internet_word', '19.7.1', 'Word: Block macros in files from the Internet',
    ['software\\policies\\microsoft\\office\\16.0\\word\\security', 'blockcontentexecutionfrominternet', 'REG_DWORD'], 1,
    'Word VBA in files with the Mark-of-the-Web is blocked outright — the control that gutted macro-phishing.',
    'Legitimate macro workbooks/templates emailed from outside get blocked; distribute them from a Trusted Location or digitally sign them. Applies per user (HKCU).',
    { scope: 'USER', allowed: EN_DIS,
      maps: { n171: ['3.14.2!'], n53: ['SI-3!', 'CM-7'], hipaa: ['164.308(a)(5)(ii)(B)'], soc2: ['CC6.8!'] } }),
  off('at_office_macro_block_internet_excel', '19.7.2', 'Excel: Block macros in files from the Internet',
    ['software\\policies\\microsoft\\office\\16.0\\excel\\security', 'blockcontentexecutionfrominternet', 'REG_DWORD'], 1,
    'Excel VBA in internet-sourced files is blocked outright.',
    'Finance teams living on emailed macro workbooks feel this hardest — set up Trusted Locations for legitimate sources.',
    { scope: 'USER', allowed: EN_DIS,
      maps: { n171: ['3.14.2!'], n53: ['SI-3!', 'CM-7'], hipaa: ['164.308(a)(5)(ii)(B)'], soc2: ['CC6.8!'] } }),
  off('at_office_macro_block_internet_ppt', '19.7.3', 'PowerPoint: Block macros in files from the Internet',
    ['software\\policies\\microsoft\\office\\16.0\\powerpoint\\security', 'blockcontentexecutionfrominternet', 'REG_DWORD'], 1,
    'PowerPoint VBA in internet-sourced files is blocked outright.',
    'Rarely felt — macro-enabled decks are uncommon.',
    { scope: 'USER', allowed: EN_DIS,
      maps: { n171: ['3.14.2!'], n53: ['SI-3!'], soc2: ['CC6.8!'] } }),
  off('at_office_vba_warnings_word', '19.7.4', 'Word: VBA macro notification — disable except digitally signed',
    ['software\\policies\\microsoft\\office\\16.0\\word\\security', 'vbawarnings', 'REG_DWORD'], 3,
    'Unsigned macros are disabled without the enable button (3); signed macros from trusted publishers still run.',
    'Every unsigned internal macro stops working for the user — inventory and sign business macros (or move to Trusted Locations) before enforcing.',
    { scope: 'USER',
      allowed: [{ value: 1, label: 'Enable all (dangerous)' }, { value: 2, label: 'Disable with notification' }, { value: 3, label: 'Disable except signed (secure)' }, { value: 4, label: 'Disable without notification' }],
      maps: { n171: ['3.14.2!'], n53: ['SI-3!', 'CM-7'], soc2: ['CC6.8!'] } }),
  off('at_office_vba_warnings_excel', '19.7.5', 'Excel: VBA macro notification — disable except digitally signed',
    ['software\\policies\\microsoft\\office\\16.0\\excel\\security', 'vbawarnings', 'REG_DWORD'], 3,
    'Unsigned Excel macros are disabled without an enable button; signed ones run.',
    'The highest-friction Office control in practice: most businesses run on unsigned Excel macros somewhere. Audit per tenant, sign what matters, then enforce.',
    { scope: 'USER',
      allowed: [{ value: 1, label: 'Enable all (dangerous)' }, { value: 2, label: 'Disable with notification' }, { value: 3, label: 'Disable except signed (secure)' }, { value: 4, label: 'Disable without notification' }],
      maps: { n171: ['3.14.2!'], n53: ['SI-3!', 'CM-7'], soc2: ['CC6.8!'] } }),
  off('at_office_vba_warnings_ppt', '19.7.6', 'PowerPoint: VBA macro notification — disable except digitally signed',
    ['software\\policies\\microsoft\\office\\16.0\\powerpoint\\security', 'vbawarnings', 'REG_DWORD'], 3,
    'Unsigned PowerPoint macros are disabled without an enable button.',
    'Rarely felt.',
    { scope: 'USER',
      allowed: [{ value: 1, label: 'Enable all (dangerous)' }, { value: 2, label: 'Disable with notification' }, { value: 3, label: 'Disable except signed (secure)' }, { value: 4, label: 'Disable without notification' }],
      maps: { n171: ['3.14.2!'], n53: ['SI-3!'], soc2: ['CC6.8!'] } }),
  off('at_office_amsi_scan', '19.7.7', 'Office: Macro Runtime Scan Scope — all documents',
    ['software\\policies\\microsoft\\office\\16.0\\common\\security', 'macroruntimescanscope', 'REG_DWORD'], 2,
    'AMSI scans macro behavior at runtime in ALL documents (2), including trusted ones — catches malicious macros that slipped through trust.',
    'Small macro performance cost; heavy legitimate macro apps may slow noticeably.',
    { scope: 'USER',
      allowed: [{ value: 0, label: 'None' }, { value: 1, label: 'Low-trust docs only' }, { value: 2, label: 'All documents (secure)' }],
      maps: { n171: ['3.14.2!'], n53: ['SI-3!'], soc2: ['CC6.8'] } }),
  off('at_office_trustbar_notification', '19.7.8', 'Office: Disable Trust Bar notification for unsigned application add-ins and block them',
    ['software\\policies\\microsoft\\office\\16.0\\common\\security', 'notbpromptunsignedaddin', 'REG_DWORD'], 1,
    'Unsigned Office add-ins are blocked silently instead of offering an enable prompt.',
    'Unsigned internal add-ins stop loading — sign them.',
    { scope: 'USER', allowed: EN_DIS,
      maps: { n171: ['3.14.2'], n53: ['SI-3', 'CM-7'], soc2: ['CC6.8'] } }),

  // --- Session lock (per-user screensaver, complements machine inactivity limit) --
  scr('at_scr_saver_active', '19.1.3.1', 'Enable screen saver (user)',
    ['software\\policies\\microsoft\\windows\\Control Panel\\Desktop', 'ScreenSaveActive', 'REG_SZ'], '1',
    'Per-user screen saver enforcement backing up the machine inactivity limit.',
    'None beyond the lock behavior itself.',
    { scope: 'USER', maps: { n171: ['3.1.10!'], n53: ['AC-11!'], hipaa: ['164.312(a)(2)(iii)!'], soc2: ['CC6.1'] } }),
  scr('at_scr_saver_secure', '19.1.3.2', 'Password protect the screen saver (user)',
    ['software\\policies\\microsoft\\windows\\Control Panel\\Desktop', 'ScreenSaverIsSecure', 'REG_SZ'], '1',
    'Resuming from the screen saver requires the password.',
    'None.',
    { scope: 'USER', maps: { n171: ['3.1.10!'], n53: ['AC-11!'], hipaa: ['164.312(a)(2)(iii)!'], soc2: ['CC6.1'] } }),
  scr('at_scr_saver_timeout', '19.1.3.3', 'Screen saver timeout: 900 seconds (user)',
    ['software\\policies\\microsoft\\windows\\Control Panel\\Desktop', 'ScreenSaveTimeOut', 'REG_SZ'], '900',
    'Screen saver engages after 15 minutes of inactivity.',
    'Same kiosk/presentation considerations as the machine inactivity limit.',
    { scope: 'USER', maps: { n171: ['3.1.10!'], n53: ['AC-11!'], hipaa: ['164.312(a)(2)(iii)!'], soc2: ['CC6.1'] } }),
];
