import { regValue, EN_DIS, type SeedEntry } from '../types';

const C = 'Security Settings > Local Policies > Security Options';
const rv = regValue(C);

export const securityOptionsEntries: SeedEntry[] = [
  // --- Accounts ---------------------------------------------------------
  rv('sec_accounts_block_ms', '2.3.1.3', 'Accounts: Block Microsoft accounts',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\NoConnectedUser', 4, 3,
    'Prevents adding or signing in with consumer Microsoft accounts (value 3 = users can neither add nor log on with them).',
    'Blocks OneDrive/Store personal sign-in flows tied to Microsoft accounts. On small-business machines actually licensed through a Microsoft account, use value 1 or exclude the machine.',
    { allowed: [{ value: 0, label: 'Allowed' }, { value: 1, label: 'Cannot add' }, { value: 3, label: 'Cannot add or log on' }],
      maps: { n171: ['3.1.1', '3.1.20'], n53: ['AC-2', 'AC-3'], soc2: ['CC6.1'] } }),
  rv('sec_accounts_limit_blank', '2.3.1.6', 'Accounts: Limit local account use of blank passwords to console logon only',
    'System\\CurrentControlSet\\Control\\Lsa\\LimitBlankPasswordUse', 4, 1,
    'Local accounts with empty passwords can only sign in at the physical console — never over the network, RDP, or remote management.',
    'If someone relies on a passwordless account for a network share or RDP (bad practice, common on home-grade setups), that stops working. Set a password instead.',
    { allowed: EN_DIS, maps: { n171: ['3.5.2!', '3.1.12'], n53: ['IA-2!', 'AC-17'], hipaa: ['164.312(d)!'], soc2: ['CC6.1'] } }),

  // --- Audit ------------------------------------------------------------
  rv('sec_audit_force_subcategory', '2.3.2.1', 'Audit: Force audit policy subcategory settings to override category settings',
    'System\\CurrentControlSet\\Control\\Lsa\\SCENoApplyLegacyAuditPolicy', 4, 1,
    'Makes the advanced (subcategory) audit policy authoritative, ignoring the legacy nine-category policy. Required for the advanced audit settings in this catalog to stick.',
    'None in practice — without it, legacy category GPOs silently clobber the advanced audit configuration.',
    { allowed: EN_DIS, maps: { n171: ['3.3.1!'], n53: ['AU-2!', 'AU-12'], hipaa: ['164.312(b)'], soc2: ['CC7.2'] } }),
  rv('sec_audit_shutdown_on_fail', '2.3.2.2', 'Audit: Shut down system immediately if unable to log security audits',
    'System\\CurrentControlSet\\Control\\Lsa\\CrashOnAuditFail', 4, 0,
    'When enabled the machine BLUE-SCREENS if the security log cannot record events. CIS recommends Disabled — availability first.',
    'Enabling this turns a full security log into a denial of service against yourself. Keep disabled unless a specific regulation demands fail-closed auditing.',
    { allowed: EN_DIS, maps: { n171: ['3.3.4'], n53: ['AU-5'], soc2: ['CC7.2'] } }),

  // --- Devices ----------------------------------------------------------
  rv('sec_devices_prevent_printer_drivers', '2.3.4.2', 'Devices: Prevent users from installing printer drivers',
    'System\\CurrentControlSet\\Control\\Print\\Providers\\LanMan Print Services\\Servers\\AddPrinterDrivers', 4, 1,
    'Only administrators may install drivers when connecting to a shared network printer (kernel drivers are code on your machine).',
    'Users adding a new shared printer whose driver is not already installed get an admin prompt — expect helpdesk tickets on fleets with many ad-hoc printers. Point and Print restrictions (separate settings) matter more post-PrintNightmare.',
    { allowed: EN_DIS, maps: { n171: ['3.4.9', '3.1.7'], n53: ['CM-11', 'AC-6'], soc2: ['CC6.8'] } }),

  // --- Domain member ----------------------------------------------------
  rv('sec_domain_encrypt_sign_always', '2.3.6.1', 'Domain member: Digitally encrypt or sign secure channel data (always)',
    'System\\CurrentControlSet\\Services\\Netlogon\\Parameters\\RequireSignOrSeal', 4, 1,
    'The machine\'s secure channel to its domain controller must always be signed or encrypted, blocking Zerologon-class tampering.',
    'Only affects domain-joined machines talking to ancient DCs (NT4-era). No effect on workgroup machines.',
    { allowed: EN_DIS, maps: { n171: ['3.13.8!'], n53: ['SC-8!'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.7'] } }),
  rv('sec_domain_encrypt_possible', '2.3.6.2', 'Domain member: Digitally encrypt secure channel data (when possible)',
    'System\\CurrentControlSet\\Services\\Netlogon\\Parameters\\SealSecureChannel', 4, 1,
    'Encrypt the domain secure channel whenever the DC supports it.',
    'None on supported environments.',
    { allowed: EN_DIS, maps: { n171: ['3.13.8!'], n53: ['SC-8!'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.7'] } }),
  rv('sec_domain_sign_possible', '2.3.6.3', 'Domain member: Digitally sign secure channel data (when possible)',
    'System\\CurrentControlSet\\Services\\Netlogon\\Parameters\\SignSecureChannel', 4, 1,
    'Sign the domain secure channel whenever the DC supports it.',
    'None on supported environments.',
    { allowed: EN_DIS, maps: { n171: ['3.13.8!'], n53: ['SC-8!'], soc2: ['CC6.7'] } }),
  rv('sec_domain_disable_pw_change', '2.3.6.4', 'Domain member: Disable machine account password changes',
    'System\\CurrentControlSet\\Services\\Netlogon\\Parameters\\DisablePasswordChange', 4, 0,
    'Keep Disabled (recommended) so the computer rotates its machine-account password on schedule.',
    'Enabling (i.e., freezing the machine password) is only ever done for VM-snapshot rollback workflows — and it weakens the machine identity. Leave at 0.',
    { allowed: EN_DIS, maps: { n171: ['3.5.2'], n53: ['IA-5'], soc2: ['CC6.1'] } }),
  rv('sec_domain_max_pw_age', '2.3.6.5', 'Domain member: Maximum machine account password age',
    'System\\CurrentControlSet\\Services\\Netlogon\\Parameters\\MaximumPasswordAge', 4, 30,
    'Rotate the machine account password every 30 days.',
    'Machines restored from old snapshots/backups beyond this window lose domain trust ("trust relationship failed") — that is the trade-off of rotation, not a reason to disable it.',
    { maps: { n171: ['3.5.2'], n53: ['IA-5'], soc2: ['CC6.1'] } }),
  rv('sec_domain_strong_key', '2.3.6.6', 'Domain member: Require strong (Windows 2000 or later) session key',
    'System\\CurrentControlSet\\Services\\Netlogon\\Parameters\\RequireStrongKey', 4, 1,
    'Require 128-bit session keys for the domain secure channel.',
    'None on any supported environment.',
    { allowed: EN_DIS, maps: { n171: ['3.13.8', '3.13.11'], n53: ['SC-8', 'SC-13'], soc2: ['CC6.7'] } }),

  // --- Interactive logon ------------------------------------------------
  rv('sec_ilogon_no_ctrl_alt_del', '2.3.7.1', 'Interactive logon: Do not require CTRL+ALT+DEL',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\DisableCAD', 4, 0,
    'Keep Disabled so users must press Ctrl+Alt+Del — the secure attention sequence that defeats fake login screens.',
    'Adds a keystroke to every sign-in. Tablet/kiosk devices without keyboards need on-screen equivalents.',
    { allowed: EN_DIS, maps: { n171: ['3.5.2'], n53: ['IA-2'], soc2: ['CC6.1'] } }),
  rv('sec_ilogon_dont_display_last', '2.3.7.2', "Interactive logon: Don't display last signed-in",
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\DontDisplayLastUserName', 4, 1,
    'The sign-in screen no longer shows the previous user\'s name, denying attackers a free valid username.',
    'Users must type their username every time — noticeable friction on shared PCs where people relied on the pre-filled tile.',
    { allowed: EN_DIS, maps: { n171: ['3.1.9', '3.5.1'], n53: ['AC-8', 'IA-4'], soc2: ['CC6.1'] } }),
  rv('sec_ilogon_machine_inactivity', '2.3.7.3', 'Interactive logon: Machine inactivity limit',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\InactivityTimeoutSecs', 4, 900,
    'Locks the session after this many seconds of inactivity (900 = 15 minutes, CIS maximum).',
    'Presentation/kiosk/dashboard machines lock mid-display — exclude those machines or lengthen their limit via a sub-policy. Videos do not count as activity.',
    { maps: { n171: ['3.1.10!'], n53: ['AC-11!'], hipaa: ['164.312(a)(2)(iii)!'], soc2: ['CC6.1'] } }),
  rv('sec_ilogon_legal_text', '2.3.7.4', 'Interactive logon: Message text for users attempting to log on',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\LegalNoticeText', 1,
    'This system is for authorized use only. Activity may be monitored and reported.',
    'Displays a legal notice banner before sign-in. Customize the text to your customer\'s counsel-approved wording.',
    'Automated test rigs that drive the login screen must acknowledge the banner. Empty text with a caption set (or vice versa) shows an odd blank dialog — set both.',
    { maps: { n171: ['3.1.9!'], n53: ['AC-8!'], soc2: ['CC6.1'] } }),
  rv('sec_ilogon_legal_caption', '2.3.7.5', 'Interactive logon: Message title for users attempting to log on',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\LegalNoticeCaption', 1, 'Authorized Use Only',
    'Title bar for the legal notice banner above.',
    'See the message text setting; set both together.',
    { maps: { n171: ['3.1.9!'], n53: ['AC-8!'], soc2: ['CC6.1'] } }),
  rv('sec_ilogon_cached_creds', '2.3.7.6', 'Interactive logon: Number of previous logons to cache',
    'Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\CachedLogonsCount', 1, '4',
    'How many domain users can sign in with cached credentials while the DC is unreachable (CIS: 4 or fewer).',
    'Laptops set to 0 cannot sign in AT ALL when off the corporate network — never set 0 on mobile devices. 4 keeps travel working while limiting the stash of crackable cached verifiers.',
    { maps: { n171: ['3.5.10'], n53: ['IA-5'], hipaa: ['164.312(d)'], soc2: ['CC6.1'] } }),
  rv('sec_ilogon_pw_expiry_warn', '2.3.7.7', 'Interactive logon: Prompt user to change password before expiration',
    'Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\PasswordExpiryWarning', 4, 14,
    'Warn users this many days before password expiry (5–14 per CIS).',
    'None.',
    { maps: { n53: ['IA-5'], soc2: ['CC6.1'] } }),
  rv('sec_ilogon_smartcard_removal', '2.3.7.9', 'Interactive logon: Smart card removal behavior',
    'Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\ScRemoveOption', 1, '1',
    'Lock the workstation when a smart card is pulled (1 = Lock).',
    'Only matters where smart cards are used for sign-in; harmless elsewhere.',
    { allowed: [{ value: '0', label: 'No action' }, { value: '1', label: 'Lock workstation' }, { value: '2', label: 'Force logoff' }, { value: '3', label: 'Disconnect RDS session' }],
      maps: { n171: ['3.1.10'], n53: ['AC-11'], hipaa: ['164.312(a)(2)(iii)'], soc2: ['CC6.1'] } }),

  // --- Microsoft network client/server (SMB signing & friends) ----------
  rv('sec_smbcli_sign_always', '2.3.8.1', 'Microsoft network client: Digitally sign communications (always)',
    'System\\CurrentControlSet\\Services\\LanmanWorkstation\\Parameters\\RequireSecuritySignature', 4, 1,
    'This machine refuses OUTBOUND SMB connections to servers that will not sign — the client half of killing SMB relay attacks.',
    'BREAKS access to shares on devices that cannot sign: consumer NAS boxes with signing off, old copiers offering scan-folder shares, and third-party SMB stacks. Test NAS/scanner flows in each tenant; fix the device or carve out an exception policy.',
    { allowed: EN_DIS, maps: { n171: ['3.13.8!', '3.13.15!'], n53: ['SC-8!', 'SC-23'], hipaa: ['164.312(e)(1)!', '164.312(c)(1)'], soc2: ['CC6.7'] } }),
  rv('sec_smbcli_sign_agree', '2.3.8.2', 'Microsoft network client: Digitally sign communications (if server agrees)',
    'System\\CurrentControlSet\\Services\\LanmanWorkstation\\Parameters\\EnableSecuritySignature', 4, 1,
    'Client offers SMB signing whenever the server supports it.',
    'None — this is the negotiate flag, not the requirement.',
    { allowed: EN_DIS, maps: { n171: ['3.13.8'], n53: ['SC-8!'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.7'] } }),
  rv('sec_smbcli_plaintext_pw', '2.3.8.3', 'Microsoft network client: Send unencrypted password to third-party SMB servers',
    'System\\CurrentControlSet\\Services\\LanmanWorkstation\\Parameters\\EnablePlainTextPassword', 4, 0,
    'Never send plaintext passwords to SMB servers, even ones that ask.',
    'Only breaks truly ancient third-party SMB servers demanding plaintext auth — replace such devices.',
    { allowed: EN_DIS, maps: { n171: ['3.5.10!', '3.13.8'], n53: ['IA-5!', 'SC-8'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.7'] } }),
  rv('sec_smbsrv_idle_timeout', '2.3.9.1', 'Microsoft network server: Amount of idle time required before suspending session',
    'System\\CurrentControlSet\\Services\\LanmanServer\\Parameters\\AutoDisconnect', 4, 15,
    'Suspend idle inbound SMB sessions after 15 minutes; sessions resume transparently on next activity.',
    'None in practice — reconnection is automatic.',
    { maps: { n171: ['3.13.9'], n53: ['SC-10!'], soc2: ['CC6.7'] } }),
  rv('sec_smbsrv_sign_always', '2.3.9.2', 'Microsoft network server: Digitally sign communications (always)',
    'System\\CurrentControlSet\\Services\\LanmanServer\\Parameters\\RequireSecuritySignature', 4, 1,
    'This machine refuses INBOUND SMB connections from clients that will not sign — the server half of killing SMB relay/NTLM relay attacks.',
    'BREAKS inbound share access from clients that cannot sign: scan-to-SMB from many older copiers/scanners, some Linux/embedded SMB clients with signing disabled, and pre-Vista clients. This is the #1 "the scanner stopped scanning" setting — check copier firmware/signing options before enforcing on machines hosting scan shares.',
    { allowed: EN_DIS, maps: { n171: ['3.13.8!', '3.13.15!'], n53: ['SC-8!', 'SC-23'], hipaa: ['164.312(e)(1)!', '164.312(c)(1)'], soc2: ['CC6.7'] } }),
  rv('sec_smbsrv_sign_agree', '2.3.9.3', 'Microsoft network server: Digitally sign communications (if client agrees)',
    'System\\CurrentControlSet\\Services\\LanmanServer\\Parameters\\EnableSecuritySignature', 4, 1,
    'Server offers SMB signing whenever the client supports it.',
    'None — negotiate flag only.',
    { allowed: EN_DIS, maps: { n171: ['3.13.8'], n53: ['SC-8!'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.7'] } }),
  rv('sec_smbsrv_force_logoff', '2.3.9.4', 'Microsoft network server: Disconnect clients when logon hours expire',
    'System\\CurrentControlSet\\Services\\LanmanServer\\Parameters\\EnableForcedLogoff', 4, 1,
    'Enforce logon-hours by cutting SMB sessions when hours end.',
    'Only matters where logon hours are configured.',
    { allowed: EN_DIS, maps: { n171: ['3.1.11'], n53: ['AC-12'], soc2: ['CC6.1'] } }),
  rv('sec_smbsrv_spn_validation', '2.3.9.5', 'Microsoft network server: Server SPN target name validation level',
    'System\\CurrentControlSet\\Services\\LanmanServer\\Parameters\\SmbServerNameHardeningLevel', 4, 1,
    'Validate the SPN a client claims when connecting (1 = Accept if provided by client), hardening against SMB relay to this host.',
    'Value 2 (Required from client) breaks older clients and some cluster/alias configurations (connecting via CNAME aliases without registered SPNs). Value 1 is the safe hardening step; test before going to 2.',
    { allowed: [{ value: 0, label: 'Off' }, { value: 1, label: 'Accept if provided by client' }, { value: 2, label: 'Required from client' }],
      maps: { n171: ['3.13.15'], n53: ['SC-23!'], soc2: ['CC6.7'] } }),

  // --- Network access ---------------------------------------------------
  rv('sec_netaccess_anon_sam', '2.3.10.2', 'Network access: Do not allow anonymous enumeration of SAM accounts',
    'System\\CurrentControlSet\\Control\\Lsa\\RestrictAnonymousSAM', 4, 1,
    'Anonymous (null-session) callers cannot list local account names — the reconnaissance step before password spraying.',
    'Essentially none on supported systems; the enumeration APIs affected are only used by ancient management tools.',
    { allowed: EN_DIS, maps: { n171: ['3.1.1!', '3.5.1'], n53: ['AC-3!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.1'] } }),
  rv('sec_netaccess_anon_sam_shares', '2.3.10.3', 'Network access: Do not allow anonymous enumeration of SAM accounts and shares',
    'System\\CurrentControlSet\\Control\\Lsa\\RestrictAnonymous', 4, 1,
    'Extends the anonymous block to share enumeration: null sessions cannot list what this machine shares.',
    'Legacy multi-domain trust scenarios and very old print servers browsing shares anonymously would fail — rare in 2020s environments.',
    { allowed: EN_DIS, maps: { n171: ['3.1.1!'], n53: ['AC-3!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.1'] } }),
  rv('sec_netaccess_no_stored_creds', '2.3.10.4', 'Network access: Do not allow storage of passwords and credentials for network authentication',
    'System\\CurrentControlSet\\Control\\Lsa\\DisableDomainCreds', 4, 1,
    'Credential Manager refuses to save domain passwords for later network use, shrinking what credential-dumping malware can harvest.',
    'HIGH friction: breaks "remember my credentials" for mapped drives, RDP saved passwords, and scheduled tasks storing credentials. Users re-enter passwords per session; scripts relying on stored credentials (cmdkey) fail. Consider tenant-by-tenant rollout.',
    { allowed: EN_DIS, maps: { n171: ['3.5.10!'], n53: ['IA-5!'], hipaa: ['164.312(d)'], soc2: ['CC6.1'] } }),
  rv('sec_netaccess_everyone_anon', '2.3.10.5', 'Network access: Let Everyone permissions apply to anonymous users',
    'System\\CurrentControlSet\\Control\\Lsa\\EveryoneIncludesAnonymous', 4, 0,
    'Keep Disabled so "Everyone" ACLs do NOT include anonymous null sessions.',
    'Only breaks setups that deliberately shared resources to anonymous users — which is the vulnerability this closes.',
    { allowed: EN_DIS, maps: { n171: ['3.1.1!'], n53: ['AC-3!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.1'] } }),
  rv('sec_netaccess_null_pipes', '2.3.10.7', 'Network access: Named Pipes that can be accessed anonymously',
    'System\\CurrentControlSet\\Services\\LanmanServer\\Parameters\\NullSessionPipes', 7, [],
    'The list of named pipes reachable without authentication. Empty (recommended) means none.',
    'Legacy fax/telephony services and pre-2008 SQL Server browsing used anonymous pipes; on modern fleets an empty list is safe.',
    { maps: { n171: ['3.1.1!'], n53: ['AC-3!'], soc2: ['CC6.1'] } }),
  rv('sec_netaccess_remote_reg_paths', '2.3.10.8', 'Network access: Remotely accessible registry paths',
    'System\\CurrentControlSet\\Control\\SecurePipeServers\\Winreg\\AllowedExactPaths\\Machine', 7,
    ['System\\CurrentControlSet\\Control\\ProductOptions', 'System\\CurrentControlSet\\Control\\Server Applications', 'Software\\Microsoft\\Windows NT\\CurrentVersion'],
    'Registry paths readable through the remote registry service, limited to the OS defaults.',
    'Monitoring products that read custom registry paths remotely (some licensing/inventory tools) need their paths appended or remote reads fail.',
    { maps: { n171: ['3.1.1'], n53: ['AC-3!'], soc2: ['CC6.1'] } }),
  rv('sec_netaccess_remote_reg_subpaths', '2.3.10.9', 'Network access: Remotely accessible registry paths and sub-paths',
    'System\\CurrentControlSet\\Control\\SecurePipeServers\\Winreg\\AllowedPaths\\Machine', 7,
    ['System\\CurrentControlSet\\Control\\Print\\Printers', 'System\\CurrentControlSet\\Services\\Eventlog', 'Software\\Microsoft\\OLAP Server', 'Software\\Microsoft\\Windows NT\\CurrentVersion\\Print', 'Software\\Microsoft\\Windows NT\\CurrentVersion\\Windows', 'System\\CurrentControlSet\\Control\\ContentIndex', 'System\\CurrentControlSet\\Control\\Terminal Server', 'System\\CurrentControlSet\\Control\\Terminal Server\\UserConfig', 'System\\CurrentControlSet\\Control\\Terminal Server\\DefaultUserConfiguration', 'Software\\Microsoft\\Windows NT\\CurrentVersion\\Perflib', 'System\\CurrentControlSet\\Services\\SysmonLog'],
    'Registry trees (including children) readable via remote registry, limited to the OS defaults.',
    'Shared-printer browsing and remote perfmon depend on entries in this default list — trimming below defaults breaks printer point-and-print browsing and remote performance counters.',
    { maps: { n171: ['3.1.1'], n53: ['AC-3!'], soc2: ['CC6.1'] } }),
  rv('sec_netaccess_restrict_null_shares', '2.3.10.10', 'Network access: Restrict anonymous access to Named Pipes and Shares',
    'System\\CurrentControlSet\\Services\\LanmanServer\\Parameters\\RestrictNullSessAccess', 4, 1,
    'Master switch: anonymous sessions can only reach pipes/shares explicitly listed in the null-session allowlists (which this baseline empties).',
    'Same considerations as the null-pipes/shares lists — modern environments are unaffected.',
    { allowed: EN_DIS, maps: { n171: ['3.1.1!'], n53: ['AC-3!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.1'] } }),
  rv('sec_netaccess_restrict_remote_sam', '2.3.10.11', 'Network access: Restrict clients allowed to make remote calls to SAM',
    'System\\CurrentControlSet\\Control\\Lsa\\RestrictRemoteSAM', 1, 'O:BAG:BAD:(A;;RC;;;BA)',
    'Only Administrators may remotely query the local account database (blocks BloodHound-style local-group reconnaissance from ordinary users).',
    'Tools that map local group membership across the fleet using non-admin service accounts (some auditing products) need their account granted in the SDDL. Requires Server 2016+/Win10 1607+ — already this platform\'s floor.',
    { maps: { n171: ['3.1.1!', '3.1.5'], n53: ['AC-3!', 'AC-6'], soc2: ['CC6.1'] } }),
  rv('sec_netaccess_null_shares', '2.3.10.12', 'Network access: Shares that can be accessed anonymously',
    'System\\CurrentControlSet\\Services\\LanmanServer\\Parameters\\NullSessionShares', 7, [],
    'Shares reachable without authentication. Empty means none.',
    'Any workgroup "drop box" share used anonymously stops working — use an authenticated account.',
    { maps: { n171: ['3.1.1!'], n53: ['AC-3!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.1'] } }),
  rv('sec_netaccess_sharing_model', '2.3.10.13', 'Network access: Sharing and security model for local accounts',
    'System\\CurrentControlSet\\Control\\Lsa\\ForceGuest', 4, 0,
    'Classic model (0, recommended): remote users authenticate as themselves. Guest-only (1) maps everyone to Guest.',
    'On home-grade workgroup setups that relied on guest-only sharing, switching to Classic makes shares prompt for real credentials — create local accounts for the users/devices (scanners!) that need access.',
    { allowed: [{ value: 0, label: 'Classic' }, { value: 1, label: 'Guest only' }],
      maps: { n171: ['3.1.1!', '3.5.1'], n53: ['AC-3!', 'IA-2'], hipaa: ['164.312(a)(1)', '164.312(d)'], soc2: ['CC6.1'] } }),

  // --- Network security -------------------------------------------------
  rv('sec_netsec_machine_id_ntlm', '2.3.11.1', 'Network security: Allow Local System to use computer identity for NTLM',
    'System\\CurrentControlSet\\Control\\Lsa\\UseMachineId', 4, 1,
    'SYSTEM services authenticate with the computer account instead of anonymously when NTLM is negotiated.',
    'None on supported systems.',
    { allowed: EN_DIS, maps: { n171: ['3.5.2'], n53: ['IA-2'], soc2: ['CC6.1'] } }),
  rv('sec_netsec_null_fallback', '2.3.11.3', 'Network security: Allow LocalSystem NULL session fallback',
    'System\\CurrentControlSet\\Control\\Lsa\\MSV1_0\\allownullsessionfallback', 4, 0,
    'Never fall back to an unauthenticated NULL session when SYSTEM NTLM auth fails.',
    'None on supported systems.',
    { allowed: EN_DIS, maps: { n171: ['3.1.1', '3.5.2'], n53: ['AC-3', 'IA-2'], soc2: ['CC6.1'] } }),
  rv('sec_netsec_online_id', '2.3.11.4', 'Network security: Allow PKU2U authentication requests to use online identities',
    'System\\CurrentControlSet\\Control\\Lsa\\pku2u\\AllowOnlineID', 4, 0,
    'Blocks peer-to-peer authentication with consumer online identities (Microsoft accounts) between machines.',
    'Azure AD-joined machines using cross-device scenarios (e.g., AAD user connecting to another AAD device\'s share by certificate) can be affected — on cloud-native fleets test share access between AAD-joined endpoints first.',
    { allowed: EN_DIS, maps: { n171: ['3.5.2'], n53: ['IA-2'], soc2: ['CC6.1'] } }),
  rv('sec_netsec_kerb_enctypes', '2.3.11.5', 'Network security: Configure encryption types allowed for Kerberos',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\Kerberos\\Parameters\\SupportedEncryptionTypes', 4, 2147483640,
    'Restrict Kerberos to AES128/AES256 and future types — RC4 and DES are off the table (value 2147483640).',
    'Domain accounts that have never rotated their password since AES support (or trusts/appliances pinned to RC4) fail Kerberos auth — symptoms are KRB_AP_ERR_MODIFIED/etype errors against old service accounts. Rotate the affected account passwords to mint AES keys.',
    { maps: { n171: ['3.13.11!'], n53: ['SC-13!'], hipaa: ['164.312(e)(2)(ii)'], soc2: ['CC6.7'] } }),
  rv('sec_netsec_no_lm_hash', '2.3.11.7', 'Network security: Do not store LAN Manager hash value on next password change',
    'System\\CurrentControlSet\\Control\\Lsa\\NoLMHash', 4, 1,
    'Stops storing the trivially-crackable LM hash of passwords.',
    'Only Windows 95/98-era clients authenticating to this machine needed LM hashes. None today.',
    { allowed: EN_DIS, maps: { n171: ['3.5.10!'], n53: ['IA-5!'], hipaa: ['164.312(a)(2)(iv)'], soc2: ['CC6.1'] } }),
  rv('sec_netsec_lm_auth_level', '2.3.11.8', 'Network security: LAN Manager authentication level',
    'System\\CurrentControlSet\\Control\\Lsa\\LmCompatibilityLevel', 4, 5,
    'Send NTLMv2 only and refuse LM & NTLMv1 as a server (level 5). NTLMv1 responses are crackable/relayable at scale.',
    'BREAKS authentication FROM devices that only speak NTLMv1: very old NAS firmware, some multifunction copiers doing scan-to-SMB, and pre-2008 OSes. If a scanner "suddenly can\'t save scans" after enforcement, check this first (and update the device firmware — most gained NTLMv2 years ago).',
    { allowed: [{ value: 0, label: 'Send LM & NTLM' }, { value: 1, label: 'LM & NTLM, NTLMv2 if negotiated' }, { value: 2, label: 'NTLM only' }, { value: 3, label: 'NTLMv2 only' }, { value: 4, label: 'NTLMv2 only / refuse LM' }, { value: 5, label: 'NTLMv2 only / refuse LM & NTLM' }],
      maps: { n171: ['3.5.4!', '3.5.10'], n53: ['IA-2!', 'IA-5'], hipaa: ['164.312(d)!'], soc2: ['CC6.1'] } }),
  rv('sec_netsec_ldap_signing', '2.3.11.9', 'Network security: LDAP client signing requirements',
    'System\\CurrentControlSet\\Services\\LDAP\\LDAPClientIntegrity', 4, 1,
    'Negotiate LDAP signing with directory servers (1 = Negotiate signing, the CIS floor).',
    '"Require" (2) breaks simple-bind apps; "Negotiate" (1) is compatible with all supported DCs and is what this baseline sets.',
    { allowed: [{ value: 0, label: 'None' }, { value: 1, label: 'Negotiate signing' }, { value: 2, label: 'Require signing' }],
      maps: { n171: ['3.13.8'], n53: ['SC-8!'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.7'] } }),
  rv('sec_netsec_ntlm_min_client', '2.3.11.10', 'Network security: Minimum session security for NTLM SSP based (including secure RPC) clients',
    'System\\CurrentControlSet\\Control\\Lsa\\MSV1_0\\NtlmMinClientSec', 4, 537395200,
    'Outbound NTLM must negotiate NTLMv2 session security AND 128-bit encryption (0x20080000).',
    'Connections to ancient services that cannot do 128-bit NTLM session security fail — same population as the LM authentication level setting.',
    { maps: { n171: ['3.13.8', '3.5.4'], n53: ['SC-8', 'IA-2'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.7'] } }),
  rv('sec_netsec_ntlm_min_server', '2.3.11.11', 'Network security: Minimum session security for NTLM SSP based (including secure RPC) servers',
    'System\\CurrentControlSet\\Control\\Lsa\\MSV1_0\\NtlmMinServerSec', 4, 537395200,
    'Inbound NTLM must negotiate NTLMv2 session security AND 128-bit encryption.',
    'Old clients (and some embedded devices) authenticating to this machine fail — see the scanner/NAS guidance on the LM level setting.',
    { maps: { n171: ['3.13.8', '3.5.4'], n53: ['SC-8', 'IA-2'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.7'] } }),
  rv('sec_netsec_ntlm_audit_outbound', '2.3.11.12', 'Network security: Restrict NTLM: Audit outgoing NTLM traffic',
    'System\\CurrentControlSet\\Control\\Lsa\\MSV1_0\\AuditSendingNTLMTraffic', 4, 2,
    'Log every outbound NTLM authentication (2 = audit all) so you can inventory NTLM dependencies before restricting them.',
    'Log volume only (Operational log NTLM). No functional impact — this is the observe step before any NTLM blocking.',
    { allowed: [{ value: 0, label: 'Disable' }, { value: 1, label: 'Audit domain accounts' }, { value: 2, label: 'Audit all' }],
      maps: { n171: ['3.3.1'], n53: ['AU-2'], soc2: ['CC7.2'] } }),

  // --- Shutdown / System objects / System settings ----------------------
  rv('sec_shutdown_without_logon', '2.3.13.1', 'Shutdown: Allow system to be shut down without having to log on',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\ShutdownWithoutLogon', 4, 0,
    'Removes the power button from the sign-in screen; only signed-in users can shut down.',
    'On physical-access kiosks people may hold the hardware power button instead — worse for the filesystem. Consider your environment.',
    { allowed: EN_DIS, maps: { n171: ['3.1.2'], n53: ['AC-6'], soc2: ['CC6.1'] } }),
  rv('sec_sysobj_case_insensitivity', '2.3.15.1', 'System objects: Require case insensitivity for non-Windows subsystems',
    'System\\CurrentControlSet\\Control\\Session Manager\\Kernel\\ObCaseInsensitive', 4, 1,
    'Forces case-insensitive object name comparisons across all subsystems, preventing case-collision spoofing tricks.',
    'None on modern systems (the POSIX subsystem this targeted is long gone).',
    { allowed: EN_DIS, maps: { n53: ['CM-6'], soc2: ['CC6.8'] } }),
  rv('sec_sysobj_strong_links', '2.3.15.2', 'System objects: Strengthen default permissions of internal system objects',
    'System\\CurrentControlSet\\Control\\Session Manager\\ProtectionMode', 4, 1,
    'Non-admin users can read shared kernel objects (DOS devices, symbolic links) but not modify ones they did not create.',
    'None on supported software.',
    { allowed: EN_DIS, maps: { n171: ['3.1.5'], n53: ['AC-6', 'CM-6'], soc2: ['CC6.3'] } }),

  // --- UAC --------------------------------------------------------------
  rv('sec_uac_admin_approval_builtin', '2.3.17.1', 'UAC: Admin Approval Mode for the Built-in Administrator account',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\FilterAdministratorToken', 4, 1,
    'Even the built-in Administrator runs with a filtered token and sees UAC prompts.',
    'Old unattended scripts running as the built-in admin that silently expected full elevation now hit UAC — convert them to scheduled tasks with highest privileges.',
    { allowed: EN_DIS, maps: { n171: ['3.1.5!', '3.1.7'], n53: ['AC-6!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.3'] } }),
  rv('sec_uac_admin_prompt', '2.3.17.2', 'UAC: Behavior of the elevation prompt for administrators in Admin Approval Mode',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\ConsentPromptBehaviorAdmin', 4, 2,
    'Admins must consent on the secure desktop for every elevation (2 = prompt for consent on the secure desktop).',
    'More clicking for admins; remote-control tools that cannot see the secure desktop appear to "hang" during elevation — pair with the secure desktop setting knowingly, and prefer tools that inject at SYSTEM level.',
    { allowed: [{ value: 0, label: 'Elevate without prompting' }, { value: 1, label: 'Prompt credentials (secure desktop)' }, { value: 2, label: 'Prompt consent (secure desktop)' }, { value: 3, label: 'Prompt credentials' }, { value: 4, label: 'Prompt consent' }, { value: 5, label: 'Consent for non-Windows binaries' }],
      maps: { n171: ['3.1.5!', '3.1.7'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  rv('sec_uac_user_prompt', '2.3.17.3', 'UAC: Behavior of the elevation prompt for standard users',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\ConsentPromptBehaviorUser', 4, 0,
    'Standard users get an automatic DENY (0) instead of a credential prompt — no over-the-shoulder admin password entry on user machines.',
    'HIGH helpdesk impact if users routinely install software with an admin typing a password at their desk: that flow now hard-fails. Techs must use their own session (runas / remote tools) instead. This is usually a process change, plan it.',
    { allowed: [{ value: 0, label: 'Automatically deny' }, { value: 1, label: 'Prompt for credentials (secure desktop)' }, { value: 3, label: 'Prompt for credentials' }],
      maps: { n171: ['3.1.5!', '3.1.7!'], n53: ['AC-6!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.3'] } }),
  rv('sec_uac_installer_detection', '2.3.17.4', 'UAC: Detect application installations and prompt for elevation',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\EnableInstallerDetection', 4, 1,
    'Heuristically detect setup programs and trigger elevation, so installers do not silently fail.',
    'None meaningful on managed fleets.',
    { allowed: EN_DIS, maps: { n171: ['3.4.9'], n53: ['CM-11'], soc2: ['CC6.8'] } }),
  rv('sec_uac_secure_uiaccess', '2.3.17.5', 'UAC: Only elevate UIAccess applications that are installed in secure locations',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\EnableSecureUIAPaths', 4, 1,
    'UI-automation apps requesting UIAccess must live in Program Files/System32 — blocks look-alike accessibility malware.',
    'Screen readers or remote-assistance tools run from user profiles lose UIAccess; install them properly instead.',
    { allowed: EN_DIS, maps: { n171: ['3.1.7'], n53: ['AC-6', 'CM-7'], soc2: ['CC6.8'] } }),
  rv('sec_uac_enable_lua', '2.3.17.6', 'UAC: Run all administrators in Admin Approval Mode',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\EnableLUA', 4, 1,
    'The master UAC switch. Never disable: without it every admin process runs fully elevated and Protected Mode/IL sandboxing collapses.',
    'A reboot is required when this changes state. Legacy line-of-business apps that "required UAC off" actually required file/registry virtualization exceptions — fix those instead of disabling UAC.',
    { allowed: EN_DIS, maps: { n171: ['3.1.5!', '3.1.7!'], n53: ['AC-6!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.3'] } }),
  rv('sec_uac_secure_desktop', '2.3.17.7', 'UAC: Switch to the secure desktop when prompting for elevation',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\PromptOnSecureDesktop', 4, 1,
    'Elevation prompts render on the isolated secure desktop where other processes cannot read or spoof them.',
    'Unattended remote support is the classic casualty: tools that only mirror the user desktop cannot see or click the prompt (session appears frozen). Tools running a SYSTEM service (most professional RMMs) handle it fine — verify yours before fleet-wide enforcement.',
    { allowed: EN_DIS, maps: { n171: ['3.1.5', '3.1.7'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  rv('sec_uac_virtualization', '2.3.17.8', 'UAC: Virtualize file and registry write failures to per-user locations',
    'Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\EnableVirtualization', 4, 1,
    'Legacy apps writing to protected paths get transparently redirected per-user instead of failing.',
    'None — disabling it is what breaks legacy apps.',
    { allowed: EN_DIS, maps: { n53: ['CM-6'], soc2: ['CC6.8'] } }),

  // --- LSA / credential protection (raw registry via secedit) -----------
  rv('sec_lsa_runasppl', '2.3.99.1', 'LSA Protection (RunAsPPL)',
    'System\\CurrentControlSet\\Control\\Lsa\\RunAsPPL', 4, 1,
    'Runs LSASS as a Protected Process Light so user-mode tools (Mimikatz and friends) cannot open and dump it, even as admin.',
    'Third-party authentication modules, smart-card middleware, and password filters that are not properly signed FAIL TO LOAD once LSASS is protected — test SSO/VPN credential providers first. Requires a reboot to take effect; on Server 2016 there is no UEFI-lock variant, so a later admin can still unset it (drift remediation will set it back).',
    { allowed: EN_DIS, maps: { n171: ['3.5.10!', '3.13.16'], n53: ['IA-5!', 'SC-28', 'SI-16'], hipaa: ['164.312(a)(2)(iv)'], soc2: ['CC6.1'] } }),
  rv('sec_wdigest_uselogoncredential', '2.3.99.2', 'WDigest: Do not store plaintext credentials in memory',
    'System\\CurrentControlSet\\Control\\SecurityProviders\\WDigest\\UseLogonCredential', 4, 0,
    'Ensures the WDigest provider never caches plaintext passwords in LSASS memory (0 = disabled, the secure state).',
    'Only breaks HTTP Digest authentication that depended on WDigest plaintext caching — effectively extinct. This is a must-set on Server 2016 fleets where attackers re-enable it to harvest passwords.',
    { allowed: [{ value: 0, label: 'Plaintext caching off (secure)' }, { value: 1, label: 'Plaintext caching on' }],
      maps: { n171: ['3.5.10!'], n53: ['IA-5!'], hipaa: ['164.312(a)(2)(iv)'], soc2: ['CC6.1'] } }),
  rv('sec_smb1_server_disable', '2.3.99.3', 'SMBv1 server: Disable',
    'System\\CurrentControlSet\\Services\\LanmanServer\\Parameters\\SMB1', 4, 0,
    'Turns off the SMBv1 protocol server-side (the EternalBlue/WannaCry surface).',
    'Pre-2008/XP clients and truly ancient scanners that can only speak SMBv1 lose access to shares on this machine. Those devices are unsafe on any network; replace them rather than re-enabling SMBv1.',
    { allowed: [{ value: 0, label: 'SMBv1 off (secure)' }, { value: 1, label: 'SMBv1 on' }],
      maps: { n171: ['3.4.6!', '3.13.8'], n53: ['CM-7!', 'SC-8'], hipaa: ['164.312(e)(1)'], soc2: ['CC6.7', 'CC7.1'] } }),
  rv('sec_smb1_client_disable', '2.3.99.4', 'SMBv1 client driver: Disable',
    'System\\CurrentControlSet\\Services\\mrxsmb10\\Start', 4, 4,
    'Disables the SMBv1 client driver (Start = 4) so this machine cannot speak SMBv1 outbound either.',
    'This machine can no longer reach shares on SMBv1-only devices (ancient NAS, some industrial equipment). Inventory old storage devices per tenant before enforcing.',
    { allowed: [{ value: 4, label: 'Disabled (secure)' }, { value: 3, label: 'Manual' }, { value: 2, label: 'Automatic' }],
      maps: { n171: ['3.4.6!', '3.13.8'], n53: ['CM-7!', 'SC-8'], soc2: ['CC6.7', 'CC7.1'] } }),
  rv('sec_sehop_enable', '2.3.99.5', 'Structured Exception Handling Overwrite Protection (SEHOP)',
    'System\\CurrentControlSet\\Control\\Session Manager\\kernel\\DisableExceptionChainValidation', 4, 0,
    'Enables SEHOP exploit mitigation process-wide (0 = validation ON).',
    'A handful of very old 32-bit applications with custom exception handling crash under SEHOP; Microsoft has shipped it default-on for servers since 2008 R2, so breakage is rare.',
    { allowed: [{ value: 0, label: 'SEHOP on (secure)' }, { value: 1, label: 'SEHOP off' }],
      maps: { n53: ['SI-16!'], soc2: ['CC6.8'] } }),

  // --- MSS legacy hardening --------------------------------------------
  rv('sec_mss_autoadminlogon', '18.4.1', 'MSS: (AutoAdminLogon) Automatic logon must be off',
    'Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\AutoAdminLogon', 1, '0',
    'Disables automatic logon, which stores a password in the registry in cleartext and signs anyone at the keyboard straight in.',
    'Kiosk/digital-signage machines intentionally using autologon break — use the dedicated kiosk configuration (assigned access) instead, or exclude those machines.',
    { maps: { n171: ['3.5.2!', '3.5.10'], n53: ['IA-2!', 'IA-5'], hipaa: ['164.312(d)'], soc2: ['CC6.1'] } }),
  rv('sec_mss_disableipsourcerouting', '18.4.2', 'MSS: (DisableIPSourceRouting) IP source routing protection level',
    'System\\CurrentControlSet\\Services\\Tcpip\\Parameters\\DisableIPSourceRouting', 4, 2,
    'Drop all source-routed IPv4 packets (2 = highest protection), a spoofing primitive.',
    'Source routing has no legitimate modern use; none.',
    { allowed: [{ value: 0, label: 'Allow all' }, { value: 1, label: 'Drop when forwarding' }, { value: 2, label: 'Drop all (secure)' }],
      maps: { n171: ['3.13.1'], n53: ['SC-7!'], soc2: ['CC6.6'] } }),
  rv('sec_mss_disableipsourcerouting6', '18.4.3', 'MSS: (DisableIPSourceRouting IPv6) IPv6 source routing protection level',
    'System\\CurrentControlSet\\Services\\Tcpip6\\Parameters\\DisableIPSourceRouting', 4, 2,
    'Drop all source-routed IPv6 packets.',
    'None.',
    { allowed: [{ value: 0, label: 'Allow all' }, { value: 1, label: 'Drop when forwarding' }, { value: 2, label: 'Drop all (secure)' }],
      maps: { n171: ['3.13.1'], n53: ['SC-7!'], soc2: ['CC6.6'] } }),
  rv('sec_mss_enableicmpredirect', '18.4.4', 'MSS: (EnableICMPRedirect) ICMP redirects must not override OSPF routes',
    'System\\CurrentControlSet\\Services\\Tcpip\\Parameters\\EnableICMPRedirect', 4, 0,
    'Ignore ICMP redirect messages, which attackers use to reroute traffic through themselves.',
    'Networks genuinely relying on ICMP redirects for routing (a design smell) would see suboptimal paths, not failures.',
    { allowed: EN_DIS, maps: { n171: ['3.13.1'], n53: ['SC-7!'], soc2: ['CC6.6'] } }),
  rv('sec_mss_nonamereleaseondemand', '18.4.6', 'MSS: (NoNameReleaseOnDemand) Ignore NetBIOS name release requests',
    'System\\CurrentControlSet\\Services\\Netbt\\Parameters\\NoNameReleaseOnDemand', 4, 1,
    'Ignore malicious NetBIOS name-release datagrams (a classic LAN denial-of-service).',
    'None.',
    { allowed: EN_DIS, maps: { n171: ['3.13.1'], n53: ['SC-7'], soc2: ['CC6.6'] } }),
  rv('sec_mss_performrouterdiscovery', '18.4.7', 'MSS: (PerformRouterDiscovery) Disable IRDP router discovery',
    'System\\CurrentControlSet\\Services\\Tcpip\\Parameters\\PerformRouterDiscovery', 4, 0,
    'Disable ICMP Router Discovery Protocol, which can be spoofed to install rogue default routes.',
    'None on networks using DHCP-assigned gateways (i.e., all of them).',
    { allowed: EN_DIS, maps: { n171: ['3.13.1'], n53: ['SC-7'], soc2: ['CC6.6'] } }),
  rv('sec_mss_safedllsearchmode', '18.4.8', 'MSS: (SafeDllSearchMode) Safe DLL search order',
    'System\\CurrentControlSet\\Control\\Session Manager\\SafeDllSearchMode', 4, 1,
    'System directories are searched before the current working directory when loading DLLs — closing classic DLL-planting attacks.',
    'Default-on since Windows XP SP2; a legacy app that shipped DLLs next to data files could theoretically load a different copy. Practically none.',
    { allowed: EN_DIS, maps: { n53: ['SI-7', 'CM-6'], soc2: ['CC6.8'] } }),
  rv('sec_mss_screensavergraceperiod', '18.4.9', 'MSS: (ScreenSaverGracePeriod) Seconds before screen saver lock takes effect',
    'Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\ScreenSaverGracePeriod', 1, '5',
    'Reduce the grace window in which moving the mouse after screensaver start skips the password (5 seconds or fewer).',
    'None meaningful.',
    { maps: { n171: ['3.1.10'], n53: ['AC-11!'], hipaa: ['164.312(a)(2)(iii)'], soc2: ['CC6.1'] } }),
  rv('sec_mss_warninglevel', '18.4.13', 'MSS: (WarningLevel) Security log near-capacity warning threshold',
    'System\\CurrentControlSet\\Services\\Eventlog\\Security\\WarningLevel', 4, 90,
    'Emit event 523 when the Security log reaches 90% capacity so collectors can react before wraparound.',
    'None.',
    { maps: { n171: ['3.3.4'], n53: ['AU-5!'], soc2: ['CC7.2'] } }),
  rv('sec_netbt_nodetype', '18.4.5', 'NetBT NodeType: P-node (point-to-point only)',
    'System\\CurrentControlSet\\Services\\NetBT\\Parameters\\NodeType', 4, 2,
    'NetBIOS resolves names via WINS only (P-node, value 2) — never broadcast, which LLMNR/NBNS spoofers (Responder) feed on.',
    'On flat LANs with no WINS/DNS entry for a legacy device reached by NetBIOS broadcast (\\\\DEVICENAME of an old NAS), name resolution fails — add a DNS record or hosts entry for it. Pair with disabling NetBIOS/LLMNR for full effect.',
    { allowed: [{ value: 1, label: 'B-node (broadcast)' }, { value: 2, label: 'P-node (secure)' }, { value: 4, label: 'M-node' }, { value: 8, label: 'H-node' }],
      maps: { n171: ['3.13.1'], n53: ['SC-7', 'SC-20?'], soc2: ['CC6.6'] } }),
];
