import { userRight, SID, type SeedEntry } from '../types';

const C = 'Security Settings > Local Policies > User Rights Assignment';
const ur = userRight(C);

const A = SID.ADMINISTRATORS;
const LS = SID.LOCAL_SERVICE;
const NS = SID.NETWORK_SERVICE;

export const userRightsEntries: SeedEntry[] = [
  ur('sec_ur_trustedcredman', '2.2.1', 'Access Credential Manager as a trusted caller', 'SeTrustedCredManAccessPrivilege', [],
    'No one should hold this right; it lets a process read other users\' saved credentials from Credential Manager during backup.',
    'Empty is the shipping default; nothing legitimate breaks.',
    { maps: { n171: ['3.1.5!'], n53: ['AC-6!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.3'] } }),
  ur('sec_ur_network_logon', '2.2.3', 'Access this computer from the network', 'SeNetworkLogonRight', [A, SID.AUTHENTICATED_USERS],
    'Who may connect over the network (SMB shares, remote registry, remote management). CIS: Administrators and Authenticated Users only — removes Everyone/anonymous.',
    'Removing Authenticated Users too (a common over-hardening) breaks ALL inbound file sharing, printer sharing, scan-to-SMB from copiers, and remote management. Workgroup machines using guest access to shares break by design here — create real accounts.',
    { maps: { n171: ['3.1.1!', '3.1.2'], n53: ['AC-3!'], hipaa: ['164.312(a)(1)!'], soc2: ['CC6.1'] } }),
  ur('sec_ur_act_as_os', '2.2.4', 'Act as part of the operating system', 'SeTcbPrivilege', [],
    'Grants complete machine takeover (any-user impersonation without authentication). Must be empty.',
    'A rare legacy service (very old backup/AV agents) may claim to need it; such software should be replaced. Empty is the shipping default.',
    { maps: { n171: ['3.1.5!'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_adjust_quotas', '2.2.6', 'Adjust memory quotas for a process', 'SeIncreaseQuotaPrivilege', [A, LS, NS],
    'Controls who can change another process\'s memory limits. Default trio is correct.',
    'SQL Server and some middleware add their service accounts here on install; re-adding those accounts to the policy value is expected on such hosts.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_logon_locally', '2.2.7', 'Allow log on locally', 'SeInteractiveLogonRight', [A, SID.USERS],
    'Who can sign in at the console/keyboard.',
    'Removing Users turns the machine into an admin-only box — fine for servers, wrong for workstations. Kiosk or shared-PC accounts must be members of a group listed here.',
    { maps: { n171: ['3.1.1!'], n53: ['AC-3!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.1'] } }),
  ur('sec_ur_rdp_logon', '2.2.9', 'Allow log on through Remote Desktop Services', 'SeRemoteInteractiveLogonRight', [A, SID.REMOTE_DESKTOP_USERS],
    'Who can start RDP sessions. Administrators plus the Remote Desktop Users group.',
    'Users who RDP into their own workstations must be added to Remote Desktop Users (group membership, not this right) or their sessions fail with "connection denied". Over-restricting this on a server admins reach only via RDP can lock out remote administration.',
    { maps: { n171: ['3.1.12!', '3.1.1'], n53: ['AC-17!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.1', 'CC6.6'] } }),
  ur('sec_ur_backup', '2.2.10', 'Back up files and directories', 'SeBackupPrivilege', [A],
    'Bypasses NTFS permissions for backup APIs. Anyone holding it can read every file on disk.',
    'Backup software using a dedicated service account needs that account listed here or backups fail with access-denied. CIS drops Backup Operators; re-add it if you actually staff that role.',
    { maps: { n171: ['3.1.5!'], n53: ['AC-6!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.3'] } }),
  ur('sec_ur_change_time', '2.2.11', 'Change the system time', 'SeSystemtimePrivilege', [A, LS],
    'Who can set the clock. Skewed clocks break Kerberos and make forensic timelines unreliable.',
    'NTP/time-sync agents running as a custom account need that account here. Users cannot change the clock — usually desired.',
    { maps: { n171: ['3.3.7!'], n53: ['AU-8!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_change_timezone', '2.2.12', 'Change the time zone', 'SeTimeZonePrivilege', [A, LS, SID.USERS],
    'Who can change the time zone (display only; does not move the underlying UTC clock).',
    'Harmless to leave Users here; removing them annoys travelers without a security gain.',
    { maps: { n53: ['AU-8'], soc2: ['CC6.3'] } }),
  ur('sec_ur_create_pagefile', '2.2.13', 'Create a pagefile', 'SeCreatePagefilePrivilege', [A],
    'Who can create/resize page files.',
    'None in practice; Administrators is the default.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_create_token', '2.2.14', 'Create a token object', 'SeCreateTokenPrivilege', [],
    'Lets a process mint arbitrary access tokens — instant SYSTEM. Must be empty.',
    'Empty is the shipping default; nothing legitimate breaks.',
    { maps: { n171: ['3.1.5!'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_create_global', '2.2.15', 'Create global objects', 'SeCreateGlobalPrivilege', [A, LS, NS, SID.SERVICE],
    'Who can create objects visible to all sessions (global named pipes/mutexes).',
    'Citrix/RDS application servers sometimes need specific app service accounts added; symptoms are apps failing only in multi-user sessions.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_create_permanent', '2.2.16', 'Create permanent shared objects', 'SeCreatePermanentPrivilege', [],
    'Kernel-mode components only; no user or service should hold it.',
    'Empty is the shipping default; nothing legitimate breaks.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_create_symlinks', '2.2.18', 'Create symbolic links', 'SeCreateSymbolicLinkPrivilege', [A],
    'Symlink creation is an ingredient in many privilege-escalation chains; restrict to Administrators.',
    'Developer machines: Docker for Windows, WSL tooling, and some build systems create symlinks — add the relevant developer group or Hyper-V "NT VIRTUAL MACHINE\\Virtual Machines" SID (S-1-5-83-0) on VM hosts, or builds fail with "A required privilege is not held".',
    { maps: { n171: ['3.1.5'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_debug', '2.2.19', 'Debug programs', 'SeDebugPrivilege', [A],
    'Attach a debugger to any process, including LSASS — the credential-dumping primitive. Administrators only (or empty on hardened servers).',
    'Developers running Visual Studio/WinDbg as non-admin need it and will fail to attach without it. Many EDR/monitoring agents hold it via their SYSTEM service instead — unaffected.',
    { maps: { n171: ['3.1.5!', '3.1.7'], n53: ['AC-6!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.3'] } }),
  ur('sec_ur_deny_network', '2.2.21', 'Deny access to this computer from the network', 'SeDenyNetworkLogonRight', [SID.GUESTS, SID.LOCAL_ACCOUNT],
    'Accounts that may NEVER connect over the network, overriding any allow. CIS adds "Local account" (S-1-5-113) to kill pass-the-hash lateral movement with local admin credentials.',
    'BREAKS workgroup remote administration by design: with S-1-5-113 denied, no local account can map shares or WinRM/WMI into this machine remotely — which is exactly the lateral-movement path being blocked. On non-domain fleets, management tools that authenticate with a local admin account will stop working; use a domain/AAD account or remove S-1-5-113 and accept the risk.',
    { maps: { n171: ['3.1.1!', '3.1.12'], n53: ['AC-3!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.1'] } }),
  ur('sec_ur_deny_batch', '2.2.22', 'Deny log on as a batch job', 'SeDenyBatchLogonRight', [SID.GUESTS],
    'Accounts that cannot run scheduled tasks configured as batch jobs.',
    'Minimal; Guests should not run scheduled tasks.',
    { maps: { n171: ['3.1.1'], n53: ['AC-3'], soc2: ['CC6.1'] } }),
  ur('sec_ur_deny_service', '2.2.23', 'Deny log on as a service', 'SeDenyServiceLogonRight', [SID.GUESTS],
    'Accounts that cannot be used to start Windows services.',
    'Minimal; Guests should not run services.',
    { maps: { n171: ['3.1.1'], n53: ['AC-3'], soc2: ['CC6.1'] } }),
  ur('sec_ur_deny_interactive', '2.2.24', 'Deny log on locally', 'SeDenyInteractiveLogonRight', [SID.GUESTS],
    'Accounts that can never sign in at the console, overriding any allow.',
    'Adding a service account here that someone also uses interactively (bad practice) locks that person out of the console.',
    { maps: { n171: ['3.1.1'], n53: ['AC-3!'], soc2: ['CC6.1'] } }),
  ur('sec_ur_deny_rdp', '2.2.26', 'Deny log on through Remote Desktop Services', 'SeDenyRemoteInteractiveLogonRight', [SID.GUESTS, SID.LOCAL_ACCOUNT],
    'Accounts that can never RDP in. CIS adds "Local account" so stolen local admin credentials cannot RDP laterally.',
    'On workgroup machines administered via RDP with a LOCAL account, adding S-1-5-113 cuts off that administration path entirely — you will need console access or a directory account to get back in. Plan the transition before enforcing.',
    { maps: { n171: ['3.1.12!', '3.1.1'], n53: ['AC-17!', 'AC-3'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.1', 'CC6.6'] } }),
  ur('sec_ur_delegation', '2.2.27', 'Enable computer and user accounts to be trusted for delegation', 'SeEnableDelegationPrivilege', [],
    'Controls who can mark accounts as trusted for Kerberos delegation. Empty on member servers/workstations.',
    'Empty is the default outside domain controllers; nothing breaks.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_remote_shutdown', '2.2.28', 'Force shutdown from a remote system', 'SeRemoteShutdownPrivilege', [A],
    'Who can shut the machine down over the network.',
    'Power-management tools using non-admin service accounts would need those accounts listed.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_generate_audits', '2.2.29', 'Generate security audits', 'SeAuditPrivilege', [LS, NS],
    'Which accounts can write entries to the Security event log via the audit API.',
    'IIS app pools and some services (ADFS) need it on specific servers; grant to those service accounts where event 4674 failures appear.',
    { maps: { n171: ['3.3.1', '3.3.8'], n53: ['AU-9!', 'AU-12'], hipaa: ['164.312(b)'], soc2: ['CC7.2'] } }),
  ur('sec_ur_impersonate', '2.2.30', 'Impersonate a client after authentication', 'SeImpersonatePrivilege', [A, LS, NS, SID.SERVICE],
    'Lets a service assume the identity of a connecting client — the privilege abused by every "Potato" escalation when granted too widely.',
    'IIS/SQL service accounts commonly require it (IIS_IUSRS is covered via SERVICE). Removing SERVICE breaks most web/app servers immediately.',
    { maps: { n171: ['3.1.5!'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_increase_priority', '2.2.31', 'Increase scheduling priority', 'SeIncreaseBasePriorityPrivilege', [A, SID.WINDOW_MANAGER],
    'Who can raise process priority to realtime levels.',
    'Window Manager group is required on Win10+ for DWM; removing it causes graphics glitches. Otherwise minimal.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6'], soc2: ['CC6.3'] } }),
  ur('sec_ur_load_driver', '2.2.32', 'Load and unload device drivers', 'SeLoadDriverPrivilege', [A],
    'Kernel driver loading — effectively kernel code execution. Administrators only.',
    'CIS historically allowed Print Operators on servers for printer drivers; modern print driver installs go through Point and Print policy instead. Rarely breaks anything as Administrators.',
    { maps: { n171: ['3.1.5!', '3.4.6'], n53: ['AC-6!', 'CM-7'], soc2: ['CC6.3'] } }),
  ur('sec_ur_lock_memory', '2.2.33', 'Lock pages in memory', 'SeLockMemoryPrivilege', [],
    'Lets a process pin memory so it never pages out. Empty by default.',
    'SQL Server performance tuning famously grants this to the SQL service account — re-add on database servers that use it, or SQL logs "cannot lock pages" warnings.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6'], soc2: ['CC6.3'] } }),
  ur('sec_ur_batch_logon', '2.2.34', 'Log on as a batch job', 'SeBatchLogonRight', [A],
    'Accounts allowed to run scheduled tasks with the "batch" logon type.',
    'Scheduled tasks running under dedicated non-admin accounts fail with 0x80070569 after tightening this — add those task accounts (or a "Batch Accounts" group) back.',
    { maps: { n171: ['3.1.1', '3.1.5'], n53: ['AC-3', 'AC-6'], soc2: ['CC6.1'] } }),
  ur('sec_ur_service_logon', '2.2.35', 'Log on as a service', 'SeServiceLogonRight', [],
    'Accounts allowed to start as Windows services. Windows grants it automatically when you assign a service account via services.msc, so an empty policy baseline is CIS-aligned — but see the risk note.',
    'ENFORCING an empty list strips the right from every existing custom service account, and those services fail to start on next restart (error 1069). Before enforcing, inventory services running as custom accounts and add those accounts/virtual accounts (e.g. NT SERVICE\\MSSQLSERVER) to the policy value.',
    { maps: { n171: ['3.1.1', '3.1.5'], n53: ['AC-3', 'AC-6'], soc2: ['CC6.1'] } }),
  ur('sec_ur_manage_audit_log', '2.2.36', 'Manage auditing and security log', 'SeSecurityPrivilege', [A],
    'Who can read/clear the Security log and change per-object auditing (SACLs). Clearing the log is how attackers cover tracks.',
    'Exchange servers require "Exchange Servers" group membership here; SIEM collectors reading the Security log with a service account need that account added or collection stops.',
    { maps: { n171: ['3.3.8!', '3.3.9!'], n53: ['AU-9!'], hipaa: ['164.312(b)'], soc2: ['CC7.2'] } }),
  ur('sec_ur_relabel', '2.2.37', 'Modify an object label', 'SeRelabelPrivilege', [],
    'Change mandatory integrity labels on objects. Empty always.',
    'Empty is the shipping default; nothing breaks.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6'], soc2: ['CC6.3'] } }),
  ur('sec_ur_firmware_env', '2.2.38', 'Modify firmware environment values', 'SeSystemEnvironmentPrivilege', [A],
    'Write UEFI variables (boot configuration).',
    'Firmware-update utilities run elevated anyway; minimal breakage.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_volume_maintenance', '2.2.39', 'Perform volume maintenance tasks', 'SeManageVolumePrivilege', [A],
    'Raw volume access (defrag, instant file initialization). Raw disk read bypasses file ACLs.',
    'SQL Server "instant file initialization" grants this to the SQL service account for fast database growth — re-add it on database servers or accept slower file allocations.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_profile_process', '2.2.40', 'Profile single process', 'SeProfileSingleProcessPrivilege', [A],
    'Sample performance of non-system processes.',
    'Monitoring agents running as non-admin may lose some per-process counters.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6'], soc2: ['CC6.3'] } }),
  ur('sec_ur_profile_system', '2.2.41', 'Profile system performance', 'SeSystemProfilePrivilege', [A, '*S-1-5-80-3139157870-2983391045-3678747466-658725712-1809340420'],
    'Sample kernel performance. The extra SID is NT SERVICE\\WdiServiceHost (Windows diagnostics), required by the OS.',
    'Removing the WdiServiceHost SID degrades built-in diagnostics; keep it.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6'], soc2: ['CC6.3'] } }),
  ur('sec_ur_assign_primary_token', '2.2.42', 'Replace a process level token', 'SeAssignPrimaryTokenPrivilege', [LS, NS],
    'Start a process under a different account\'s token (parent-to-child). Service duo only.',
    'IIS and SQL service accounts occasionally need it (WMI providers, out-of-process apps); symptom is CreateProcessAsUser failing with 1314.',
    { maps: { n171: ['3.1.5!'], n53: ['AC-6!'], soc2: ['CC6.3'] } }),
  ur('sec_ur_restore', '2.2.43', 'Restore files and directories', 'SeRestorePrivilege', [A],
    'Bypasses NTFS permissions when writing — restore can overwrite anything, and it also allows taking ownership indirectly.',
    'Backup/restore software service accounts need it to restore; same considerations as the Backup right.',
    { maps: { n171: ['3.1.5!'], n53: ['AC-6!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.3'] } }),
  ur('sec_ur_shutdown', '2.2.44', 'Shut down the system', 'SeShutdownPrivilege', [A, SID.USERS],
    'Who can shut down/restart from the local console.',
    'Removing Users on workstations means only admins can shut down — irritating and usually unnecessary. On servers, Administrators-only is standard (set per-policy).',
    { maps: { n171: ['3.1.2'], n53: ['AC-6'], soc2: ['CC6.3'] } }),
  ur('sec_ur_sync_agent', '2.2.45', 'Synchronize directory service data', 'SeSyncAgentPrivilege', [],
    'Domain-controller-only right (DirSync). Empty everywhere else.',
    'Empty is the default off DCs; nothing breaks.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6'], soc2: ['CC6.3'] } }),
  ur('sec_ur_take_ownership', '2.2.46', 'Take ownership of files or other objects', 'SeTakeOwnershipPrivilege', [A],
    'Seize ownership of any securable object, defeating NTFS permissions.',
    'Administrators-only is the default; nothing legitimate breaks.',
    { maps: { n171: ['3.1.5!'], n53: ['AC-6!'], hipaa: ['164.312(a)(1)'], soc2: ['CC6.3'] } }),
  ur('sec_ur_machine_account', '2.2.5', 'Add workstations to domain', 'SeMachineAccountPrivilege', [A],
    'Domain-controller right controlling who can join computers to the domain; harmless but defined for completeness on members.',
    'Only meaningful on domain controllers. No effect on standalone machines.',
    { maps: { n171: ['3.1.5'], n53: ['AC-6'], soc2: ['CC6.3'] } }),
  ur('sec_ur_traverse', '2.2.2', 'Bypass traverse checking', 'SeChangeNotifyPrivilege', [A, LS, NS, SID.USERS, SID.EVERYONE],
    'Pass through folders you cannot list while reaching files you can access. Broad grant is the OS default and required for normal operation.',
    'Narrowing this below the default breaks file access in bizarre, hard-to-diagnose ways (profile load failures, apps unable to open files). Keep the default membership.',
    { maps: { n53: ['AC-6'], soc2: ['CC6.3'] } }),
];
